// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

namespace BB84.SourceGenerators.Helpers;

/// <summary>
/// A lightweight wrapper around <see cref="StringBuilder"/> that provides automatic
/// indentation tracking and common code generation patterns for source generators.
/// </summary>
internal sealed class SourceBuilder
{
	private const int IndentSize = 2;
	private const int MaxIndentLevels = 20;
	private static readonly string[] Indents =
		[.. Enumerable.Range(0, MaxIndentLevels).Select(i => new string(' ', i * IndentSize))];
	private readonly StringBuilder _sb = new();

	/// <summary>
	/// Gets the current indentation level.
	/// </summary>
	public int IndentLevel { get; private set; }

	/// <summary>
	/// Appends an auto-generated warning comment block.
	/// </summary>
	/// <param name="toolName">The name of the tool that generated the code.</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder AppendAutoGeneratedWarning(string toolName)
	{
		_sb.AppendLine("//------------------------------------------------------------------------------");
		_sb.AppendLine("// <auto-generated>");
		_sb.AppendLine("//     This code was generated by a tool.");
		_sb.AppendLine($"//     Tool: {toolName}");
		_sb.AppendLine("//");
		_sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
		_sb.AppendLine("//     the code is regenerated.");
		_sb.AppendLine("// </auto-generated>");
		_sb.AppendLine("//------------------------------------------------------------------------------");
		return this;
	}

	/// <summary>
	/// Appends the <c>#nullable enable</c> directive.
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder AppendNullableEnable()
	{
		_sb.AppendLine("#nullable enable");
		return this;
	}

	/// <summary>
	/// Appends a using directive.
	/// </summary>
	/// <param name="namespace">The namespace to import.</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder AppendUsing(string @namespace)
	{
		_sb.AppendLine($"using {@namespace};");
		return this;
	}

	/// <summary>
	/// Opens a namespace block with the given name.
	/// </summary>
	/// <param name="namespaceName">The namespace name.</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder OpenNamespace(string namespaceName)
	{
		AppendLine($"namespace {namespaceName}");
		OpenBrace();
		return this;
	}

	/// <summary>
	/// Closes the current namespace block.
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder CloseNamespace()
	{
		CloseBrace();
		return this;
	}

	/// <summary>
	/// Opens outer (nesting) class declarations for the given list of outer classes.
	/// </summary>
	/// <param name="outerClasses">The list of outer classes from outermost to innermost.</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder OpenOuterClasses(List<(string Accessibility, string Name)> outerClasses)
	{
		foreach ((string accessibility, string name) in outerClasses)
		{
			AppendLine($"{accessibility} partial class {name}");
			OpenBrace();
		}

		return this;
	}

	/// <summary>
	/// Closes outer (nesting) class declarations.
	/// </summary>
	/// <param name="outerClasses">The list of outer classes (used only for count).</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder CloseOuterClasses(List<(string Accessibility, string Name)> outerClasses)
	{
		for (int i = 0; i < outerClasses.Count; i++)
			CloseBrace();

		return this;
	}

	/// <summary>
	/// Opens a class declaration.
	/// </summary>
	/// <param name="accessibility">The accessibility modifier.</param>
	/// <param name="className">The class name.</param>
	/// <param name="baseTypes">Optional base types / interfaces to implement.</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder OpenClass(string accessibility, string className, string? baseTypes = null)
	{
		if (baseTypes is not null)
			AppendLine($"{accessibility} partial class {className} : {baseTypes}");
		else
			AppendLine($"{accessibility} partial class {className}");

		OpenBrace();
		return this;
	}

	/// <summary>
	/// Opens a sealed class declaration.
	/// </summary>
	/// <param name="accessibility">The accessibility modifier.</param>
	/// <param name="className">The class name.</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder OpenSealedClass(string accessibility, string className)
	{
		AppendLine($"{accessibility} sealed class {className}");
		OpenBrace();
		return this;
	}

	/// <summary>
	/// Closes the current class block.
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder CloseClass()
	{
		CloseBrace();
		return this;
	}

	/// <summary>
	/// Appends a line with the current indentation followed by the specified text.
	/// </summary>
	/// <param name="text">The text to append.</param>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder AppendLine(string text)
	{
		_sb.Append(IndentLevel < MaxIndentLevels ? Indents[IndentLevel] : new string(' ', IndentLevel * IndentSize));
		_sb.AppendLine(text);
		return this;
	}

	/// <summary>
	/// Appends an empty line.
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder AppendLine()
	{
		_sb.AppendLine();
		return this;
	}

	/// <summary>
	/// Opens a brace block (appends '{' and increases indentation).
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder OpenBrace()
	{
		_sb.Append(IndentLevel < MaxIndentLevels ? Indents[IndentLevel] : new string(' ', IndentLevel * IndentSize));
		_sb.AppendLine("{");
		IndentLevel++;
		return this;
	}

	/// <summary>
	/// Closes a brace block (decreases indentation and appends '}').
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder CloseBrace()
	{
		IndentLevel--;
		_sb.Append(IndentLevel < MaxIndentLevels ? Indents[IndentLevel] : new string(' ', IndentLevel * IndentSize));
		_sb.AppendLine("}");
		return this;
	}

	/// <summary>
	/// Increases the indentation level by one.
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder Indent()
	{
		IndentLevel++;
		return this;
	}

	/// <summary>
	/// Decreases the indentation level by one.
	/// </summary>
	/// <returns>The current <see cref="SourceBuilder"/> instance.</returns>
	public SourceBuilder Outdent()
	{
		if (IndentLevel > 0)
			IndentLevel--;
		return this;
	}

	/// <inheritdoc/>
	public override string ToString()
		=> _sb.ToString();
}
