// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
namespace BB84.SourceGenerators.Attributes;

/// <summary>
/// Indicates that the decorated field should be excluded from notification property generation.
/// Fields marked with this attribute will not have properties generated by the
/// <see cref="GenerateNotificationsAttribute"/> source generator.
/// </summary>
[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
internal sealed class ExcludeFromNotificationAttribute : Attribute
{
}
