// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating compile-time constant properties for assembly information
/// on classes marked with the <see cref="GenerateAssemblyInformationAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AssemblyInformationGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorAttributeName = typeof(GenerateAssemblyInformationAttribute).FullName;

	private static readonly (string AttributeName, string PropertyName)[] AssemblyAttributes =
	[
		("System.Reflection.AssemblyTitleAttribute", "Title"),
		("System.Reflection.AssemblyDescriptionAttribute", "Description"),
		("System.Reflection.AssemblyCompanyAttribute", "Company"),
		("System.Reflection.AssemblyProductAttribute", "Product"),
		("System.Reflection.AssemblyCopyrightAttribute", "Copyright"),
		("System.Reflection.AssemblyTrademarkAttribute", "Trademark"),
		("System.Reflection.AssemblyConfigurationAttribute", "Configuration"),
		("System.Reflection.AssemblyVersionAttribute", "Version"),
		("System.Reflection.AssemblyFileVersionAttribute", "FileVersion"),
		("System.Reflection.AssemblyInformationalVersionAttribute", "InformationalVersion"),
		("System.Runtime.Versioning.TargetFrameworkAttribute", "TargetFramework"),
		("System.Resources.NeutralResourcesLanguageAttribute", "NeutralResourcesLanguage")
	];

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		(Dictionary<string, string> assemblyValues, Dictionary<string, List<string>> allAssemblyValues) = GetAssemblyAttributeValues(ctx.SemanticModel.Compilation);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.AssemblyInformationGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendUsing(NamespaceNames.SystemCollectionsGeneric);
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, assemblyValues, allAssemblyValues);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.AssemblyInformation.g.cs"
			: $"{ctx.ClassName}.AssemblyInformation.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, Dictionary<string, string> assemblyValues, Dictionary<string, List<string>> allAssemblyValues)
	{
		sb.OpenClass(accessibility, className);

		bool first = true;
		foreach ((string attributeName, string propertyName) in AssemblyAttributes)
		{
			if (!first)
				sb.AppendLine();

			first = false;

			string value = assemblyValues.TryGetValue(attributeName, out string? v) ? v : string.Empty;
			string escaped = GeneratorHelpers.EscapeString(value);

			sb.AppendLine("/// <summary>");
			sb.AppendLine($"/// Gets the assembly {propertyName.ToLowerInvariant()} information.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine($"public const string {propertyName} = \"{escaped}\";");
		}

		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Gets all assembly attributes available at compile time.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("public static readonly Dictionary<string, List<string>> Attributes = new(StringComparer.Ordinal)");
		sb.AppendLine("{");
		sb.Indent();

		foreach (KeyValuePair<string, List<string>> item in allAssemblyValues)
		{
			string escapedKey = GeneratorHelpers.EscapeString(item.Key);
			string values = string.Join(", ", item.Value.Select(v => $"\"{GeneratorHelpers.EscapeString(v)}\""));
			sb.AppendLine($"[\"{escapedKey}\"] = new List<string> {{ {values} }},");
		}

		sb.Outdent();
		sb.AppendLine("};");

		sb.CloseClass();
	}

	private static (Dictionary<string, string> AssemblyValues, Dictionary<string, List<string>> AllAssemblyValues) GetAssemblyAttributeValues(Compilation compilation)
	{
		Dictionary<string, string> values = new(StringComparer.Ordinal);
		Dictionary<string, List<string>> allValues = new(StringComparer.Ordinal);

		foreach (AttributeData attribute in compilation.Assembly.GetAttributes())
		{
			string? fullName = attribute.AttributeClass?.ToDisplayString();
			if (fullName is null)
				continue;

			string value = GetAttributeValue(attribute);
			values[fullName] = value;

			if (AssemblyAttributes.Any(x => x.AttributeName == fullName))
				continue;

			if (!allValues.TryGetValue(fullName, out List<string>? attributeValues))
			{
				attributeValues = [];
				allValues[fullName] = attributeValues;
			}

			attributeValues.Add(value);
		}

		return (values, allValues);
	}

	private static string GetAttributeValue(AttributeData attribute)
	{
		List<string> parts = [];

		if (attribute.ConstructorArguments.Length > 0)
			parts.Add(string.Join(", ", attribute.ConstructorArguments.Select(FormatTypedConstant)));

		if (attribute.NamedArguments.Length > 0)
			parts.Add(string.Join(", ", attribute.NamedArguments.Select(arg => $"{arg.Key}={FormatTypedConstant(arg.Value)}")));

		return parts.Count > 0
			? string.Join("; ", parts)
			: string.Empty;
	}

	private static string FormatTypedConstant(TypedConstant constant)
	{
		return constant.IsNull
			? string.Empty
			: constant.Kind == TypedConstantKind.Array
			? string.Join(", ", constant.Values.Select(FormatTypedConstant))
			: constant.Value?.ToString() ?? string.Empty;
	}
}
