// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a fluent builder class for classes marked
/// with the <see cref="GenerateBuilderAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BuilderGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorAttributeName = typeof(GenerateBuilderAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		string builderClassName = $"{ctx.ClassName}Builder";

		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, requireSetter: true);

		if (properties.Length == 0)
			return;

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.BuilderGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendBuilderClass(sb, ctx.ClassName, builderClassName, ctx.Accessibility, properties);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{builderClassName}.g.cs"
			: $"{builderClassName}.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendBuilderClass(SourceBuilder sb, string className, string builderClassName, string accessibility, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// A fluent builder for creating instances of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.OpenSealedClass(accessibility, builderClassName);

		// Fields
		foreach (PropertyDescriptor prop in properties)
		{
			string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name[1..]}";
			string typeName = prop.IsReferenceType && prop.IsNullable ? $"{prop.TypeName}?" : prop.TypeName;
			string initializer = prop.IsReferenceType && !prop.IsNullable ? " = default!;" : ";";
			sb.AppendLine($"private {typeName} {fieldName}{initializer}");
		}

		sb.AppendLine();

		// With methods
		foreach (PropertyDescriptor prop in properties)
		{
			string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name[1..]}";
			string typeName = prop.IsReferenceType && prop.IsNullable ? $"{prop.TypeName}?" : prop.TypeName;
			sb.AppendLine("/// <summary>");
			sb.AppendLine($"/// Sets the value for the <see cref=\"{className}.{prop.Name}\"/> property.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine("/// <param name=\"value\">The value to set.</param>");
			sb.AppendLine("/// <returns>The current builder instance.</returns>");
			sb.AppendLine($"public {builderClassName} With{prop.Name}({typeName} value)");
			sb.OpenBrace();
			sb.AppendLine($"{fieldName} = value;");
			sb.AppendLine("return this;");
			sb.CloseBrace();
			sb.AppendLine();
		}

		// Build method
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Creates a new instance of <see cref=\"{className}\"/> with the configured property values.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <returns>A new <see cref=\"{className}\"/> instance.</returns>");
		sb.AppendLine($"public {className} Build()");
		sb.OpenBrace();
		sb.AppendLine($"return new {className}()");
		sb.OpenBrace();

		for (int i = 0; i < properties.Length; i++)
		{
			PropertyDescriptor prop = properties[i];
			string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name[1..]}";
			string separator = i < properties.Length - 1 ? "," : string.Empty;
			sb.AppendLine($"{prop.Name} = {fieldName}{separator}");
		}

		sb.Outdent();
		sb.AppendLine("};");
		sb.CloseBrace();
		sb.CloseClass();
	}
}
