// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a fluent builder class for classes marked
/// with the <see cref="GenerateBuilderAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BuilderGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(BuilderGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateBuilderAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GeneratorHelpers.GetAccessibility(classDeclaration);
		string builderClassName = $"{className}Builder";

		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(classSymbol, requireSetter: true);

		if (properties.Length == 0)
			return;

		List<(string Accessibility, string Name)> outerClasses = GeneratorHelpers.GetOuterClasses(classDeclaration);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in outerClasses)
		{
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{indent}{{");
			baseIndent++;
		}

		AppendBuilderClass(sb, className, builderClassName, accessibility, properties, baseIndent);

		for (int i = outerClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}}}");
		}

		sb.AppendLine("}");

		string hintName = outerClasses.Count > 0
			? $"{string.Join(".", outerClasses.Select(o => o.Name))}.{builderClassName}.g.cs"
			: $"{builderClassName}.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendBuilderClass(StringBuilder sb, string className, string builderClassName, string accessibility, ImmutableArray<PropertyDescriptor> properties, int indentLevel = 1)
	{
		string indent = new(' ', indentLevel * 2);
		string innerIndent = new(' ', (indentLevel + 1) * 2);
		string bodyIndent = new(' ', (indentLevel + 2) * 2);

		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// A fluent builder for creating instances of <see cref=\"{className}\"/>.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}{accessibility} sealed class {builderClassName}");
		sb.AppendLine($"{indent}{{");

		// Fields
		foreach (PropertyDescriptor prop in properties)
		{
			string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name.Substring(1)}";
			string typeName = prop.IsReferenceType && prop.IsNullable ? $"{prop.TypeName}?" : prop.TypeName;
			string initializer = prop.IsReferenceType && !prop.IsNullable ? " = default!;" : ";";
			sb.AppendLine($"{innerIndent}private {typeName} {fieldName}{initializer}");
		}

		sb.AppendLine();

		// With methods
		foreach (PropertyDescriptor prop in properties)
		{
			string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name.Substring(1)}";
			string typeName = prop.IsReferenceType && prop.IsNullable ? $"{prop.TypeName}?" : prop.TypeName;
			sb.AppendLine($"{innerIndent}/// <summary>");
			sb.AppendLine($"{innerIndent}/// Sets the value for the <see cref=\"{className}.{prop.Name}\"/> property.");
			sb.AppendLine($"{innerIndent}/// </summary>");
			sb.AppendLine($"{innerIndent}/// <param name=\"value\">The value to set.</param>");
			sb.AppendLine($"{innerIndent}/// <returns>The current builder instance.</returns>");
			sb.AppendLine($"{innerIndent}public {builderClassName} With{prop.Name}({typeName} value)");
			sb.AppendLine($"{innerIndent}{{");
			sb.AppendLine($"{bodyIndent}{fieldName} = value;");
			sb.AppendLine($"{bodyIndent}return this;");
			sb.AppendLine($"{innerIndent}}}");
			sb.AppendLine();
		}

		// Build method
		sb.AppendLine($"{innerIndent}/// <summary>");
		sb.AppendLine($"{innerIndent}/// Creates a new instance of <see cref=\"{className}\"/> with the configured property values.");
		sb.AppendLine($"{innerIndent}/// </summary>");
		sb.AppendLine($"{innerIndent}/// <returns>A new <see cref=\"{className}\"/> instance.</returns>");
		sb.AppendLine($"{innerIndent}public {className} Build()");
		sb.AppendLine($"{innerIndent}{{");
		sb.AppendLine($"{bodyIndent}return new {className}()");
		sb.AppendLine($"{bodyIndent}{{");

		string deepIndent = new(' ', (indentLevel + 3) * 2);
		for (int i = 0; i < properties.Length; i++)
		{
			PropertyDescriptor prop = properties[i];
			string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name.Substring(1)}";
			string separator = i < properties.Length - 1 ? "," : string.Empty;
			sb.AppendLine($"{deepIndent}{prop.Name} = {fieldName}{separator}");
		}

		sb.AppendLine($"{bodyIndent}}};");
		sb.AppendLine($"{innerIndent}}}");

		sb.AppendLine($"{indent}}}");
	}
}
