// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating clone methods for classes marked
/// with the <see cref="GenerateCloneableAttribute"/> attribute. The generated code includes
/// a <c>Clone()</c> method for shallow copying and a <c>DeepClone()</c> method that
/// recursively deep clones reference-type properties also marked with
/// <see cref="GenerateCloneableAttribute"/>, implementing <c>ICloneable</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CloneableGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(CloneableGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateCloneableAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GeneratorHelpers.GetAccessibility(classDeclaration);

		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(classDeclaration, semanticModel, "GenerateCloneable", "GenerateCloneableAttribute");
		ImmutableArray<PropertyInfo> properties = GetPublicProperties(classSymbol, excludedProperties);

		List<(string Accessibility, string Name)> outerClasses = GeneratorHelpers.GetOuterClasses(classDeclaration);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using System;");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in outerClasses)
		{
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{indent}{{");
			baseIndent++;
		}

		AppendPartialClass(sb, className, accessibility, properties, baseIndent);

		for (int i = outerClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}}}");
		}

		sb.AppendLine("}");

		string hintName = outerClasses.Count > 0
			? $"{string.Join(".", outerClasses.Select(o => o.Name))}.{className}.Cloneable.g.cs"
			: $"{className}.Cloneable.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, ImmutableArray<PropertyInfo> properties, int indentLevel = 1)
	{
		string indent = new(' ', indentLevel * 2);

		sb.AppendLine($"{indent}{accessibility} partial class {className} : ICloneable");
		sb.AppendLine($"{indent}{{");

		AppendCloneMethod(sb, className, properties, indentLevel + 1);
		sb.AppendLine();
		AppendDeepCloneMethod(sb, className, properties, indentLevel + 1);
		sb.AppendLine();
		AppendICloneableClone(sb, indentLevel + 1);

		sb.AppendLine($"{indent}}}");
	}

	private static void AppendCloneMethod(StringBuilder sb, string className, ImmutableArray<PropertyInfo> properties, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Creates a shallow copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}/// <returns>A new <see cref=\"{className}\"/> instance with the same property values.</returns>");
		sb.AppendLine($"{indent}public {className} Clone()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}{className} clone = new {className}();");

		foreach (PropertyInfo property in properties)
			sb.AppendLine($"{bodyIndent}clone.{property.Name} = this.{property.Name};");

		sb.AppendLine($"{bodyIndent}return clone;");
		sb.AppendLine($"{indent}}}");
	}

	private static void AppendDeepCloneMethod(StringBuilder sb, string className, ImmutableArray<PropertyInfo> properties, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Creates a deep copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine($"{indent}/// Reference-type properties marked with <c>[GenerateCloneable]</c> are recursively deep cloned.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}/// <returns>A new <see cref=\"{className}\"/> instance with deeply cloned property values.</returns>");
		sb.AppendLine($"{indent}public {className} DeepClone()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}{className} clone = new {className}();");

		foreach (PropertyInfo property in properties)
		{
			if (property.IsCloneable)
			{
				sb.AppendLine($"{bodyIndent}clone.{property.Name} = this.{property.Name}?.DeepClone();");
			}
			else
			{
				sb.AppendLine($"{bodyIndent}clone.{property.Name} = this.{property.Name};");
			}
		}

		sb.AppendLine($"{bodyIndent}return clone;");
		sb.AppendLine($"{indent}}}");
	}

	private static void AppendICloneableClone(StringBuilder sb, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}/// <inheritdoc/>");
		sb.AppendLine($"{indent}object ICloneable.Clone()");
		sb.AppendLine($"{bodyIndent}=> DeepClone();");
	}

	private static ImmutableArray<PropertyInfo> GetPublicProperties(INamedTypeSymbol classSymbol, HashSet<string> excludedProperties)
	{
		ImmutableArray<PropertyInfo>.Builder builder = ImmutableArray.CreateBuilder<PropertyInfo>();

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			if (propertySymbol.DeclaredAccessibility != Accessibility.Public)
				continue;

			if (propertySymbol.IsStatic || propertySymbol.IsReadOnly || propertySymbol.IsWriteOnly)
				continue;

			if (propertySymbol.GetMethod is null || propertySymbol.SetMethod is null)
				continue;

			if (excludedProperties.Contains(propertySymbol.Name))
				continue;

			bool isCloneable = HasGenerateCloneableAttribute(propertySymbol.Type);

			builder.Add(new PropertyInfo(propertySymbol.Name, isCloneable));
		}

		return builder.ToImmutable();
	}

	private static bool HasGenerateCloneableAttribute(ITypeSymbol typeSymbol)
	{
		foreach (AttributeData attributeData in typeSymbol.GetAttributes())
			if (attributeData.AttributeClass?.ToDisplayString() == GeneratorAttributeName)
				return true;

		return false;
	}

	private readonly struct PropertyInfo(string name, bool isCloneable)
	{
		public string Name { get; } = name;
		public bool IsCloneable { get; } = isCloneable;
	}
}
