// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating clone methods for classes marked
/// with the <see cref="GenerateCloneableAttribute"/> attribute. The generated code includes
/// a <c>Clone()</c> method for shallow copying and a <c>DeepClone()</c> method that
/// recursively deep clones reference-type properties also marked with
/// <see cref="GenerateCloneableAttribute"/>, implementing <c>ICloneable</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CloneableGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(CloneableGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateCloneableAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(ctx.ClassDeclaration, ctx.SemanticModel, nameof(GenerateCloneableAttribute));
		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, excludedProperties, requireSetter: true, cloneableAttributeName: GeneratorAttributeName);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendNullableEnable();
		sb.AppendUsing("System");
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, properties);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.Cloneable.g.cs"
			: $"{ctx.ClassName}.Cloneable.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.OpenClass(accessibility, className, "ICloneable");

		AppendCloneMethod(sb, className, properties);
		sb.AppendLine();
		AppendDeepCloneMethod(sb, className, properties);
		sb.AppendLine();
		AppendICloneableClone(sb);

		sb.CloseClass();
	}

	private static void AppendCloneMethod(SourceBuilder sb, string className, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Creates a shallow copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <returns>A new <see cref=\"{className}\"/> instance with the same property values.</returns>");
		sb.AppendLine($"public {className} Clone()");
		sb.OpenBrace();
		sb.AppendLine($"{className} clone = new {className}();");

		foreach (PropertyDescriptor property in properties)
			sb.AppendLine($"clone.{property.Name} = this.{property.Name};");

		sb.AppendLine("return clone;");
		sb.CloseBrace();
	}

	private static void AppendDeepCloneMethod(SourceBuilder sb, string className, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Creates a deep copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine("/// Reference-type properties marked with <c>[GenerateCloneable]</c> are recursively deep cloned.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <returns>A new <see cref=\"{className}\"/> instance with deeply cloned property values.</returns>");
		sb.AppendLine($"public {className} DeepClone()");
		sb.OpenBrace();
		sb.AppendLine($"{className} clone = new {className}();");

		foreach (PropertyDescriptor property in properties)
		{
			if (property.IsCloneable)
				sb.AppendLine($"clone.{property.Name} = this.{property.Name}?.DeepClone();");
			else
				sb.AppendLine($"clone.{property.Name} = this.{property.Name};");
		}

		sb.AppendLine("return clone;");
		sb.CloseBrace();
	}

	private static void AppendICloneableClone(SourceBuilder sb)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("object ICloneable.Clone()");
		sb.Indent();
		sb.AppendLine("=> DeepClone();");
		sb.Outdent();
	}
}
