// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating clone methods for classes marked
/// with the <see cref="GenerateCloneableAttribute"/> attribute. The generated code includes
/// a <c>Clone()</c> method for shallow copying and a <c>DeepClone()</c> method that
/// recursively deep clones reference-type properties also marked with
/// <see cref="GenerateCloneableAttribute"/>, implementing <c>ICloneable</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CloneableGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(CloneableGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateCloneableAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(ctx.ClassDeclaration, ctx.SemanticModel, "GenerateCloneable", "GenerateCloneableAttribute");
		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, excludedProperties, requireSetter: true, cloneableAttributeName: GeneratorAttributeName);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using System;");
		sb.AppendLine();
		sb.AppendLine($"namespace {ctx.NamespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in ctx.OuterClasses)
		{
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{indent}{{");
			baseIndent++;
		}

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, properties, baseIndent);

		for (int i = ctx.OuterClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}}}");
		}

		sb.AppendLine("}");

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.Cloneable.g.cs"
			: $"{ctx.ClassName}.Cloneable.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, ImmutableArray<PropertyDescriptor> properties, int indentLevel = 1)
	{
		string indent = new(' ', indentLevel * 2);

		sb.AppendLine($"{indent}{accessibility} partial class {className} : ICloneable");
		sb.AppendLine($"{indent}{{");

		AppendCloneMethod(sb, className, properties, indentLevel + 1);
		sb.AppendLine();
		AppendDeepCloneMethod(sb, className, properties, indentLevel + 1);
		sb.AppendLine();
		AppendICloneableClone(sb, indentLevel + 1);

		sb.AppendLine($"{indent}}}");
	}

	private static void AppendCloneMethod(StringBuilder sb, string className, ImmutableArray<PropertyDescriptor> properties, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Creates a shallow copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}/// <returns>A new <see cref=\"{className}\"/> instance with the same property values.</returns>");
		sb.AppendLine($"{indent}public {className} Clone()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}{className} clone = new {className}();");

		foreach (PropertyDescriptor property in properties)
			sb.AppendLine($"{bodyIndent}clone.{property.Name} = this.{property.Name};");

		sb.AppendLine($"{bodyIndent}return clone;");
		sb.AppendLine($"{indent}}}");
	}

	private static void AppendDeepCloneMethod(StringBuilder sb, string className, ImmutableArray<PropertyDescriptor> properties, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Creates a deep copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine($"{indent}/// Reference-type properties marked with <c>[GenerateCloneable]</c> are recursively deep cloned.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}/// <returns>A new <see cref=\"{className}\"/> instance with deeply cloned property values.</returns>");
		sb.AppendLine($"{indent}public {className} DeepClone()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}{className} clone = new {className}();");

		foreach (PropertyDescriptor property in properties)
		{
			if (property.IsCloneable)
			{
				sb.AppendLine($"{bodyIndent}clone.{property.Name} = this.{property.Name}?.DeepClone();");
			}
			else
			{
				sb.AppendLine($"{bodyIndent}clone.{property.Name} = this.{property.Name};");
			}
		}

		sb.AppendLine($"{bodyIndent}return clone;");
		sb.AppendLine($"{indent}}}");
	}

	private static void AppendICloneableClone(StringBuilder sb, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}/// <inheritdoc/>");
		sb.AppendLine($"{indent}object ICloneable.Clone()");
		sb.AppendLine($"{bodyIndent}=> DeepClone();");
	}
}
