// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;

using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating the dispose pattern for classes marked
/// with the <see cref="GenerateDisposableAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DisposableGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(DisposableGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateDisposableAttribute).FullName;
	private const string AttributeFullName = nameof(GenerateDisposableAttribute);
	private static readonly string AttributeShortName = GeneratorHelpers.StripAttributeSuffix(AttributeFullName);
	private const string DisposeResourceFullName = nameof(DisposeResourceAttribute);
	private static readonly string DisposeResourceShortName = GeneratorHelpers.StripAttributeSuffix(DisposeResourceFullName);

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		(bool generateFinalizer, bool generateAsync) = GetAttributeOptions(ctx.ClassDeclaration);

		// Check if IAsyncDisposable is available in the target framework
		if (generateAsync)
		{
			INamedTypeSymbol? asyncDisposableSymbol = ctx.SemanticModel.Compilation
				.GetTypeByMetadataName("System.IAsyncDisposable");

			if (asyncDisposableSymbol is null)
			{
				Diagnostic diagnostic = Diagnostic.Create(
					DiagnosticDescriptors.AsyncDisposableNotSupportedDiagnostic,
					ctx.ClassDeclaration.Identifier.GetLocation(),
					ctx.ClassName);
				context.ReportDiagnostic(diagnostic);
				generateAsync = false;
			}
		}

		bool isSealed = ctx.ClassDeclaration.Modifiers.Any(SyntaxKind.SealedKeyword);

		ImmutableArray<(string FieldName, int Order, int SourceIndex)> disposableFields = GetDisposableFields(ctx.ClassDeclaration);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendNullableEnable();
		AppendUsings(sb, generateAsync);
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendClassStart(sb, ctx.ClassName, ctx.Accessibility, generateAsync);
		AppendDisposedField(sb);
		AppendThrowIfDisposed(sb, ctx.ClassName, isSealed);
		AppendDisposeBool(sb, disposableFields, isSealed);
		AppendDisposePublic(sb);

		if (generateFinalizer)
			AppendFinalizer(sb, ctx.ClassName);

		if (generateAsync)
		{
			AppendDisposeAsyncCore(sb, disposableFields, isSealed);
			AppendDisposeAsync(sb);
		}

		sb.CloseClass();
		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.Disposable.g.cs"
			: $"{ctx.ClassName}.Disposable.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static (bool generateFinalizer, bool generateAsync) GetAttributeOptions(ClassDeclarationSyntax classDeclaration)
	{
		bool generateFinalizer = false;
		bool generateAsync = false;

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != AttributeShortName && name != AttributeFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return (generateFinalizer, generateAsync);

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string? paramName = argument.NameColon?.Name.Identifier.Text;
					string argText = argument.Expression.ToString();

					if (!bool.TryParse(argText, out bool value))
						continue;

					switch (paramName)
					{
						case "generateFinalizer":
							generateFinalizer = value;
							break;
						case "async":
							generateAsync = value;
							break;
						default:
							int index = attribute.ArgumentList.Arguments.IndexOf(argument);
							if (index == 0)
								generateFinalizer = value;
							else if (index == 1)
								generateAsync = value;
							break;
					}
				}

				return (generateFinalizer, generateAsync);
			}
		}

		return (generateFinalizer, generateAsync);
	}

	private static ImmutableArray<(string FieldName, int Order, int SourceIndex)> GetDisposableFields(ClassDeclarationSyntax classDeclaration)
	{
		List<(string FieldName, int Order, int SourceIndex)> fields = [];
		int sourceIndex = 0;

		foreach (MemberDeclarationSyntax member in classDeclaration.Members)
		{
			if (member is not FieldDeclarationSyntax fieldDeclaration)
				continue;

			int order = GetDisposeResourceOrder(fieldDeclaration);

			if (order < 0)
			{
				sourceIndex++;
				continue;
			}

			foreach (VariableDeclaratorSyntax variable in fieldDeclaration.Declaration.Variables)
			{
				fields.Add((variable.Identifier.Text, order, sourceIndex));
				sourceIndex++;
			}
		}

		// Non-zero orders first (ascending), then zero-order fields in source order
		fields.Sort((a, b) =>
		{
			return a.Order != 0 && b.Order != 0
				? a.Order.CompareTo(b.Order)
				: a.Order != 0 ? -1 : b.Order != 0 ? 1 : a.SourceIndex.CompareTo(b.SourceIndex);
		});

		return [.. fields];
	}

	/// <summary>
	/// Returns the order value if the field has [DisposeResource], or -1 if not present.
	/// </summary>
	private static int GetDisposeResourceOrder(FieldDeclarationSyntax fieldDeclaration)
	{
		foreach (AttributeListSyntax attributeList in fieldDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != DisposeResourceShortName && name != DisposeResourceFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return 0;

				AttributeArgumentSyntax firstArg = attribute.ArgumentList.Arguments[0];
				string argText = firstArg.Expression.ToString();

				return int.TryParse(argText, out int order) ? order : 0;
			}
		}

		return -1;
	}

	private static void AppendUsings(SourceBuilder sb, bool generateAsync)
	{
		sb.AppendUsing("System");
		if (generateAsync)
			sb.AppendUsing("System.Threading.Tasks");
		sb.AppendLine();
	}

	private static void AppendClassStart(SourceBuilder sb, string className, string accessibility, bool generateAsync)
	{
		string interfaces = generateAsync ? "IDisposable, IAsyncDisposable" : "IDisposable";
		sb.OpenClass(accessibility, className, interfaces);
	}

	private static void AppendDisposedField(SourceBuilder sb)
	{
		sb.AppendLine("private bool _disposed;");
		sb.AppendLine();
	}

	private static void AppendThrowIfDisposed(SourceBuilder sb, string className, bool isSealed)
	{
		string modifier = isSealed ? "private" : "protected";
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Throws <see cref=\"ObjectDisposedException\"/> if this instance has been disposed.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"{modifier} void ThrowIfDisposed()");
		sb.OpenBrace();
		sb.AppendLine("if (_disposed)");
		sb.Indent();
		sb.AppendLine($"throw new ObjectDisposedException(nameof({className}));");
		sb.Outdent();
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendDisposeBool(SourceBuilder sb, ImmutableArray<(string FieldName, int Order, int SourceIndex)> fields, bool isSealed)
	{
		string modifier = isSealed ? "private" : "protected virtual";
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Releases managed and optionally unmanaged resources.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"disposing\">");
		sb.AppendLine("/// <see langword=\"true\"/> to release both managed and unmanaged resources;");
		sb.AppendLine("/// <see langword=\"false\"/> to release only unmanaged resources.");
		sb.AppendLine("/// </param>");
		sb.AppendLine($"{modifier} void Dispose(bool disposing)");
		sb.OpenBrace();
		sb.AppendLine("if (!_disposed)");
		sb.OpenBrace();
		sb.AppendLine("if (disposing)");
		sb.OpenBrace();

		foreach ((string fieldName, int _, int _) in fields)
			sb.AppendLine($"{fieldName}?.Dispose();");

		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("_disposed = true;");
		sb.CloseBrace();
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendDisposePublic(SourceBuilder sb)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public void Dispose()");
		sb.OpenBrace();
		sb.AppendLine("Dispose(true);");
		sb.AppendLine("GC.SuppressFinalize(this);");
		sb.CloseBrace();
	}

	private static void AppendFinalizer(SourceBuilder sb, string className)
	{
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Finalizer for <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"~{className}()");
		sb.OpenBrace();
		sb.AppendLine("Dispose(false);");
		sb.CloseBrace();
	}

	private static void AppendDisposeAsyncCore(SourceBuilder sb, ImmutableArray<(string FieldName, int Order, int SourceIndex)> fields, bool isSealed)
	{
		string modifier = isSealed ? "private" : "protected virtual";
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Performs application-defined tasks associated with freeing, releasing,");
		sb.AppendLine("/// or resetting managed resources asynchronously.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <returns>A task that represents the asynchronous dispose operation.</returns>");
		sb.AppendLine($"{modifier} async ValueTask DisposeAsyncCore()");
		sb.OpenBrace();

		foreach ((string fieldName, int _, int _) in fields)
		{
			sb.AppendLine($"if ({fieldName} is IAsyncDisposable {fieldName}Async)");
			sb.Indent();
			sb.AppendLine($"await {fieldName}Async.DisposeAsync().ConfigureAwait(false);");
			sb.Outdent();
			sb.AppendLine("else");
			sb.Indent();
			sb.AppendLine($"{fieldName}?.Dispose();");
			sb.Outdent();
			sb.AppendLine();
		}

		sb.CloseBrace();
	}

	private static void AppendDisposeAsync(SourceBuilder sb)
	{
		sb.AppendLine();
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public async ValueTask DisposeAsync()");
		sb.OpenBrace();
		sb.AppendLine("await DisposeAsyncCore().ConfigureAwait(false);");
		sb.AppendLine("Dispose(false);");
		sb.AppendLine("GC.SuppressFinalize(this);");
		sb.CloseBrace();
	}
}
