// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating the dispose pattern for classes marked
/// with the <see cref="GenerateDisposableAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DisposableGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(DisposableGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateDisposableAttribute).FullName;
	private const string AttributeShortName = "GenerateDisposable";
	private const string AttributeFullName = "GenerateDisposableAttribute";
	private const string DisposeResourceShortName = "DisposeResource";
	private const string DisposeResourceFullName = "DisposeResourceAttribute";

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		(bool generateFinalizer, bool generateAsync) = GetAttributeOptions(ctx.ClassDeclaration);

		// Check if IAsyncDisposable is available in the target framework
		if (generateAsync)
		{
			INamedTypeSymbol? asyncDisposableSymbol = ctx.SemanticModel.Compilation
				.GetTypeByMetadataName("System.IAsyncDisposable");

			if (asyncDisposableSymbol is null)
			{
				Diagnostic diagnostic = Diagnostic.Create(
					DiagnosticDescriptors.AsyncDisposableNotSupportedDiagnostic,
					ctx.ClassDeclaration.Identifier.GetLocation(),
					ctx.ClassName);
				context.ReportDiagnostic(diagnostic);
				generateAsync = false;
			}
		}

		bool isSealed = ctx.ClassDeclaration.Modifiers.Any(SyntaxKind.SealedKeyword);

		ImmutableArray<(string FieldName, int Order, int SourceIndex)> disposableFields = GetDisposableFields(ctx.ClassDeclaration);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		AppendUsings(sb, generateAsync);
		sb.AppendLine($"namespace {ctx.NamespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in ctx.OuterClasses)
		{
			string ind = new(' ', baseIndent * 2);
			sb.AppendLine($"{ind}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{ind}{{");
			baseIndent++;
		}

		AppendClassStart(sb, ctx.ClassName, ctx.Accessibility, generateAsync, baseIndent);
		AppendDisposedField(sb, baseIndent + 1);
		AppendThrowIfDisposed(sb, ctx.ClassName, isSealed, baseIndent + 1);
		AppendDisposeBool(sb, disposableFields, isSealed, baseIndent + 1);
		AppendDisposePublic(sb, baseIndent + 1);

		if (generateFinalizer)
			AppendFinalizer(sb, ctx.ClassName, baseIndent + 1);

		if (generateAsync)
		{
			AppendDisposeAsyncCore(sb, disposableFields, isSealed, baseIndent + 1);
			AppendDisposeAsync(sb, baseIndent + 1);
		}

		string classIndent = new(' ', baseIndent * 2);
		sb.AppendLine($"{classIndent}}}");

		for (int i = ctx.OuterClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string ind = new(' ', baseIndent * 2);
			sb.AppendLine($"{ind}}}");
		}

		sb.AppendLine("}");

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.Disposable.g.cs"
			: $"{ctx.ClassName}.Disposable.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static (bool generateFinalizer, bool generateAsync) GetAttributeOptions(ClassDeclarationSyntax classDeclaration)
	{
		bool generateFinalizer = false;
		bool generateAsync = false;

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not AttributeShortName and not AttributeFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return (generateFinalizer, generateAsync);

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string? paramName = argument.NameColon?.Name.Identifier.Text;
					string argText = argument.Expression.ToString();

					if (!bool.TryParse(argText, out bool value))
						continue;

					switch (paramName)
					{
						case "generateFinalizer":
							generateFinalizer = value;
							break;
						case "async":
							generateAsync = value;
							break;
						default:
							int index = attribute.ArgumentList.Arguments.IndexOf(argument);
							if (index == 0)
								generateFinalizer = value;
							else if (index == 1)
								generateAsync = value;
							break;
					}
				}

				return (generateFinalizer, generateAsync);
			}
		}

		return (generateFinalizer, generateAsync);
	}

	private static ImmutableArray<(string FieldName, int Order, int SourceIndex)> GetDisposableFields(ClassDeclarationSyntax classDeclaration)
	{
		List<(string FieldName, int Order, int SourceIndex)> fields = [];
		int sourceIndex = 0;

		foreach (MemberDeclarationSyntax member in classDeclaration.Members)
		{
			if (member is not FieldDeclarationSyntax fieldDeclaration)
				continue;

			int order = GetDisposeResourceOrder(fieldDeclaration);

			if (order < 0)
			{
				sourceIndex++;
				continue;
			}

			foreach (VariableDeclaratorSyntax variable in fieldDeclaration.Declaration.Variables)
			{
				fields.Add((variable.Identifier.Text, order, sourceIndex));
				sourceIndex++;
			}
		}

		// Non-zero orders first (ascending), then zero-order fields in source order
		fields.Sort((a, b) =>
		{
			return a.Order != 0 && b.Order != 0
				? a.Order.CompareTo(b.Order)
				: a.Order != 0 ? -1 : b.Order != 0 ? 1 : a.SourceIndex.CompareTo(b.SourceIndex);
		});

		return [.. fields];
	}

	/// <summary>
	/// Returns the order value if the field has [DisposeResource], or -1 if not present.
	/// </summary>
	private static int GetDisposeResourceOrder(FieldDeclarationSyntax fieldDeclaration)
	{
		foreach (AttributeListSyntax attributeList in fieldDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not DisposeResourceShortName and not DisposeResourceFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return 0;

				AttributeArgumentSyntax firstArg = attribute.ArgumentList.Arguments[0];
				string argText = firstArg.Expression.ToString();

				return int.TryParse(argText, out int order) ? order : 0;
			}
		}

		return -1;
	}

	private static void AppendUsings(StringBuilder sb, bool generateAsync)
	{
		sb.AppendLine("using System;");
		if (generateAsync)
			sb.AppendLine("using System.Threading.Tasks;");
		sb.AppendLine();
	}

	private static void AppendClassStart(StringBuilder sb, string className, string accessibility, bool generateAsync, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);

		string interfaces = generateAsync ? "IDisposable, IAsyncDisposable" : "IDisposable";
		sb.AppendLine($"{indent}{accessibility} partial class {className} : {interfaces}");
		sb.AppendLine($"{indent}{{");
	}

	private static void AppendDisposedField(StringBuilder sb, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);

		sb.AppendLine($"{indent}private bool _disposed;");
		sb.AppendLine();
	}

	private static void AppendThrowIfDisposed(StringBuilder sb, string className, bool isSealed, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);
		string deepIndent = new(' ', (indentLevel + 2) * 2);

		string modifier = isSealed ? "private" : "protected";
		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Throws <see cref=\"ObjectDisposedException\"/> if this instance has been disposed.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}{modifier} void ThrowIfDisposed()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}if (_disposed)");
		sb.AppendLine($"{deepIndent}throw new ObjectDisposedException(nameof({className}));");
		sb.AppendLine($"{indent}}}");
		sb.AppendLine();
	}

	private static void AppendDisposeBool(StringBuilder sb, ImmutableArray<(string FieldName, int Order, int SourceIndex)> fields, bool isSealed, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);
		string deepIndent = new(' ', (indentLevel + 2) * 2);
		string deeperIndent = new(' ', (indentLevel + 3) * 2);

		string modifier = isSealed ? "private" : "protected virtual";
		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Releases managed and optionally unmanaged resources.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}/// <param name=\"disposing\">");
		sb.AppendLine($"{indent}/// <see langword=\"true\"/> to release both managed and unmanaged resources;");
		sb.AppendLine($"{indent}/// <see langword=\"false\"/> to release only unmanaged resources.");
		sb.AppendLine($"{indent}/// </param>");
		sb.AppendLine($"{indent}{modifier} void Dispose(bool disposing)");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}if (!_disposed)");
		sb.AppendLine($"{bodyIndent}{{");
		sb.AppendLine($"{deepIndent}if (disposing)");
		sb.AppendLine($"{deepIndent}{{");

		foreach ((string fieldName, int _, int _) in fields)
			sb.AppendLine($"{deeperIndent}{fieldName}?.Dispose();");

		sb.AppendLine($"{deepIndent}}}");
		sb.AppendLine();
		sb.AppendLine($"{deepIndent}_disposed = true;");
		sb.AppendLine($"{bodyIndent}}}");
		sb.AppendLine($"{indent}}}");
		sb.AppendLine();
	}

	private static void AppendDisposePublic(StringBuilder sb, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}/// <inheritdoc/>");
		sb.AppendLine($"{indent}public void Dispose()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}Dispose(true);");
		sb.AppendLine($"{bodyIndent}GC.SuppressFinalize(this);");
		sb.AppendLine($"{indent}}}");
	}

	private static void AppendFinalizer(StringBuilder sb, string className, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine();
		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Finalizer for <see cref=\"{className}\"/>.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}~{className}()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}Dispose(false);");
		sb.AppendLine($"{indent}}}");
	}

	private static void AppendDisposeAsyncCore(StringBuilder sb, ImmutableArray<(string FieldName, int Order, int SourceIndex)> fields, bool isSealed, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);
		string deepIndent = new(' ', (indentLevel + 2) * 2);

		string modifier = isSealed ? "private" : "protected virtual";
		sb.AppendLine();
		sb.AppendLine($"{indent}/// <summary>");
		sb.AppendLine($"{indent}/// Performs application-defined tasks associated with freeing, releasing,");
		sb.AppendLine($"{indent}/// or resetting managed resources asynchronously.");
		sb.AppendLine($"{indent}/// </summary>");
		sb.AppendLine($"{indent}/// <returns>A task that represents the asynchronous dispose operation.</returns>");
		sb.AppendLine($"{indent}{modifier} async ValueTask DisposeAsyncCore()");
		sb.AppendLine($"{indent}{{");

		foreach ((string fieldName, int _, int _) in fields)
		{
			sb.AppendLine($"{bodyIndent}if ({fieldName} is IAsyncDisposable {fieldName}Async)");
			sb.AppendLine($"{deepIndent}await {fieldName}Async.DisposeAsync().ConfigureAwait(false);");
			sb.AppendLine($"{bodyIndent}else");
			sb.AppendLine($"{deepIndent}{fieldName}?.Dispose();");
			sb.AppendLine();
		}

		sb.AppendLine($"{indent}}}");
	}

	private static void AppendDisposeAsync(StringBuilder sb, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine();
		sb.AppendLine($"{indent}/// <inheritdoc/>");
		sb.AppendLine($"{indent}public async ValueTask DisposeAsync()");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{bodyIndent}await DisposeAsyncCore().ConfigureAwait(false);");
		sb.AppendLine($"{bodyIndent}Dispose(false);");
		sb.AppendLine($"{bodyIndent}GC.SuppressFinalize(this);");
		sb.AppendLine($"{indent}}}");
	}
}
