// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating enumerator extensions for enumerators marked
/// with the <see cref="GenerateEnumeratorExtensionsAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EnumeratorExtensionsGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorAttributeName = typeof(GenerateEnumeratorExtensionsAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(EnumDeclarationSyntax EnumDeclaration, SemanticModel SemanticModel)> provider = context.SyntaxProvider
			 .ForAttributeWithMetadataName(
				 fullyQualifiedMetadataName: GeneratorAttributeName,
				 predicate: (node, _) => Predicate(node),
				transform: (context, _) => Transform(context));

		context.RegisterSourceOutput(provider, Execute);
	}

	/// <inheritdoc/>
	private void Execute(SourceProductionContext context, (EnumDeclarationSyntax EnumDeclaration, SemanticModel SemanticModel) data)
	{
		EnumDeclarationSyntax enumDeclaration = data.EnumDeclaration;

		ImmutableArray<EnumMemberDeclarationSyntax> members = [.. enumDeclaration.Members
				.OfType<EnumMemberDeclarationSyntax>()
				.Where(field => field is not null)];

		if (!members.Any())
			return;

		string enumName = enumDeclaration.Identifier.Text;
		string enumNamespace = enumDeclaration.GetNamespace();

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.EnumeratorExtensionsGeneratorFullName);
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendUsing(NamespaceNames.SystemComponentModel);
		sb.AppendLine();
		sb.OpenNamespace(enumNamespace);

		AppendClassStart(sb, enumName);

		AppendToStringFast(sb, enumName, members);
		AppendIsDefinedFast(sb, enumName, members);
		AppendGetDescriptionFast(sb, enumName, members, data.SemanticModel);
		AppendGetNamesFast(sb, enumName, members);
		AppendGetValuesFast(sb, enumName, members);

		sb.CloseClass();
		sb.CloseNamespace();

		context.AddSource($"{enumName}.g.cs", sb.ToString());
	}

	/// <inheritdoc/>
	private static (EnumDeclarationSyntax EnumDeclaration, SemanticModel SemanticModel) Transform(GeneratorAttributeSyntaxContext context)
		=> ((EnumDeclarationSyntax)context.TargetNode, context.SemanticModel);

	/// <inheritdoc/>
	private static bool Predicate(SyntaxNode node)
		=> node is EnumDeclarationSyntax;

	private static void AppendClassStart(SourceBuilder sb, string enumName)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// The <see cref=\"{enumName}Extensions\"/> class provides extension methods for the <see cref=\"{enumName}\"/> enumeration.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"public static class {enumName}Extensions");
		sb.OpenBrace();
	}

	private static void AppendToStringFast(SourceBuilder sb, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Returns the name of the enumeration <paramref name=\"value\"/> as a string.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"value\">The enumeration value to convert to a string.</param>");
		sb.AppendLine("/// <returns>The name of the enumeration value as a string.</returns>");
		sb.AppendLine($"public static string ToStringFast(this {enumName} value)");
		sb.OpenBrace();
		sb.AppendLine("return value switch");
		sb.OpenBrace();
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			sb.AppendLine($"{enumName}.{memberName} => nameof({enumName}.{memberName}),");
		}
		sb.AppendLine("_ => value.ToString()");
		sb.Outdent();
		sb.AppendLine("};");
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendIsDefinedFast(SourceBuilder sb, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Returns whether the specified enumeration <paramref name=\"value\"/> is defined");
		sb.AppendLine($"/// in the <see cref=\"{enumName}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"value\">The enumeration value to check.</param>");
		sb.AppendLine("/// <returns>True if the enumeration value is defined; otherwise, false.</returns>");
		sb.AppendLine($"public static bool IsDefinedFast(this {enumName} value)");
		sb.OpenBrace();
		sb.AppendLine("return value switch");
		sb.OpenBrace();
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			sb.AppendLine($"{enumName}.{memberName} => true,");
		}
		sb.AppendLine("_ => false");
		sb.Outdent();
		sb.AppendLine("};");
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Returns whether the specified enumeration <paramref name=\"name\"/> is defined");
		sb.AppendLine($"/// in the <see cref=\"{enumName}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"name\">The name of the enumeration value to check.</param>");
		sb.AppendLine("/// <returns>True if the enumeration value is defined; otherwise, false.</returns>");
		sb.AppendLine($"public static bool IsDefinedFast(string name)");
		sb.OpenBrace();
		sb.AppendLine("return name switch");
		sb.OpenBrace();
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			sb.AppendLine($"nameof({enumName}.{memberName}) => true,");
		}
		sb.AppendLine("_ => false");
		sb.Outdent();
		sb.AppendLine("};");
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendGetNamesFast(SourceBuilder sb, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Returns the names of the <see cref=\"{enumName}\"/> enumeration as an collection of strings.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"value\">The enumeration value to get the names for.</param>");
		sb.AppendLine("/// <returns>An array of strings containing the names of the enumeration values.</returns>");
		sb.AppendLine($"public static IEnumerable<string> GetNamesFast(this {enumName} value)");
		sb.OpenBrace();
		sb.AppendLine("return new[]");
		sb.OpenBrace();
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			sb.AppendLine($"nameof({enumName}.{memberName}),");
		}
		sb.Outdent();
		sb.AppendLine("};");
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendGetValuesFast(SourceBuilder sb, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Returns the values of the <see cref=\"{enumName}\"/> enumeration.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"value\">The enumeration value to get the values for.</param>");
		sb.AppendLine("/// <returns>An collection of the enumeration values.</returns>");
		sb.AppendLine($"public static IEnumerable<{enumName}> GetValuesFast(this {enumName} value)");
		sb.OpenBrace();
		sb.AppendLine("return new[]");
		sb.OpenBrace();
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			sb.AppendLine($"{enumName}.{memberName},");
		}
		sb.Outdent();
		sb.AppendLine("};");
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendGetDescriptionFast(SourceBuilder sb, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members, SemanticModel semanticModel)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Returns the description of the <see cref=\"{enumName}\"/> enumeration if the");
		sb.AppendLine("/// <see cref=\"System.ComponentModel.DescriptionAttribute\"/> is applied to the");
		sb.AppendLine("/// enumeration value; otherwise, returns the name of the enumeration value.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"value\">The enumeration value to get the description for.</param>");
		sb.AppendLine("/// <returns>The description of the enumeration value, or its name if no description is set.</returns>");
		sb.AppendLine($"public static string GetDescriptionFast(this {enumName} value)");
		sb.OpenBrace();
		sb.AppendLine("return value switch");
		sb.OpenBrace();
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			string? description = GetDescriptionFromAttributes(member, semanticModel);

			if (description is not null)
				sb.AppendLine($"{enumName}.{memberName} => \"{description}\",");
			else
				sb.AppendLine($"{enumName}.{memberName} => nameof({enumName}.{memberName}),");
		}
		sb.AppendLine("_ => value.ToString()");
		sb.Outdent();
		sb.AppendLine("};");
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static string? GetDescriptionFromAttributes(EnumMemberDeclarationSyntax member, SemanticModel semanticModel)
	{
		INamedTypeSymbol? descriptionAttributeSymbol = semanticModel.Compilation.GetTypeByMetadataName("System.ComponentModel.DescriptionAttribute");

		if (descriptionAttributeSymbol is null)
			return null;

		foreach (AttributeListSyntax attributeList in member.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				SymbolInfo symbolInfo = semanticModel.GetSymbolInfo(attribute);
				if (symbolInfo.Symbol is not IMethodSymbol attributeConstructor)
					continue;

				if (!SymbolEqualityComparer.Default.Equals(attributeConstructor.ContainingType, descriptionAttributeSymbol))
					continue;

				if (attribute.ArgumentList?.Arguments.Count > 0)
				{
					AttributeArgumentSyntax argument = attribute.ArgumentList.Arguments[0];
					Optional<object?> descriptionValue = semanticModel.GetConstantValue(argument.Expression);

					return descriptionValue.HasValue && descriptionValue.Value is string description
						? description
						: argument.ToString().Trim('"');
				}
			}
		}

		return null;
	}
}
