// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating equality members for classes marked
/// with the <see cref="GenerateEqualityAttribute"/> attribute. The generated code includes
/// <c>Equals(object)</c>, <c>Equals(T)</c>, <c>GetHashCode()</c>,
/// <c>operator ==</c>, and <c>operator !=</c>, implementing <c>IEquatable&lt;T&gt;</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EqualityGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorAttributeName = typeof(GenerateEqualityAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(ctx.ClassDeclaration, ctx.SemanticModel, nameof(GenerateEqualityAttribute));
		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, excludedProperties);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.EqualityGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, properties);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.Equality.g.cs"
			: $"{ctx.ClassName}.Equality.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.OpenClass(accessibility, className, $"IEquatable<{className}>");

		AppendEqualsObject(sb, className);
		sb.AppendLine();
		AppendEqualsT(sb, className, properties);
		sb.AppendLine();
		AppendGetHashCode(sb, properties);
		sb.AppendLine();
		AppendOperatorEquals(sb, className);
		sb.AppendLine();
		AppendOperatorNotEquals(sb, className);

		sb.CloseClass();
	}

	private static void AppendEqualsObject(SourceBuilder sb, string className)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public override bool Equals(object? obj)");
		sb.Indent();
		sb.AppendLine($"=> Equals(obj as {className});");
		sb.Outdent();
	}

	private static void AppendEqualsT(SourceBuilder sb, string className, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine($"public bool Equals({className}? other)");
		sb.OpenBrace();
		sb.AppendLine("if (other is null)");
		sb.Indent();
		sb.AppendLine("return false;");
		sb.Outdent();
		sb.AppendLine();
		sb.AppendLine("if (ReferenceEquals(this, other))");
		sb.Indent();
		sb.AppendLine("return true;");
		sb.Outdent();

		if (properties.Length > 0)
		{
			sb.AppendLine();

			StringBuilder returnExpr = new();
			returnExpr.Append("return ");

			for (int i = 0; i < properties.Length; i++)
			{
				if (i > 0)
					returnExpr.Append("\n" + new string(' ', (sb.IndentLevel + 1) * 2) + "&& ");

				returnExpr.Append($"Equals({properties[i].Name}, other.{properties[i].Name})");
			}

			returnExpr.Append(';');
			sb.AppendLine(returnExpr.ToString());
		}
		else
		{
			sb.AppendLine();
			sb.AppendLine("return true;");
		}

		sb.CloseBrace();
	}

	private static void AppendGetHashCode(SourceBuilder sb, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public override int GetHashCode()");
		sb.OpenBrace();

		if (properties.Length == 0)
		{
			sb.AppendLine("return base.GetHashCode();");
		}
		else
		{
			sb.AppendLine("unchecked");
			sb.OpenBrace();
			sb.AppendLine("int hash = 17;");

			foreach (PropertyDescriptor property in properties)
			{
				if (property.IsValueType)
					sb.AppendLine($"hash = hash * 31 + {property.Name}.GetHashCode();");
				else
					sb.AppendLine($"hash = hash * 31 + ({property.Name}?.GetHashCode() ?? 0);");
			}

			sb.AppendLine("return hash;");
			sb.CloseBrace();
		}

		sb.CloseBrace();
	}

	private static void AppendOperatorEquals(SourceBuilder sb, string className)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Determines whether two <see cref=\"{className}\"/> instances are equal.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"public static bool operator ==({className}? left, {className}? right)");
		sb.Indent();
		sb.AppendLine("=> Equals(left, right);");
		sb.Outdent();
	}

	private static void AppendOperatorNotEquals(SourceBuilder sb, string className)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Determines whether two <see cref=\"{className}\"/> instances are not equal.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"public static bool operator !=({className}? left, {className}? right)");
		sb.Indent();
		sb.AppendLine("=> !Equals(left, right);");
		sb.Outdent();
	}
}
