// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating equality members for classes marked
/// with the <see cref="GenerateEqualityAttribute"/> attribute. The generated code includes
/// <c>Equals(object)</c>, <c>Equals(T)</c>, <c>GetHashCode()</c>,
/// <c>operator ==</c>, and <c>operator !=</c>, implementing <c>IEquatable&lt;T&gt;</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EqualityGenerator : IIncrementalGenerator
{
	private const int HashSeed = 17;
	private const int HashFactor = 31;
	private const string EnumerableTypeName = NamespaceNames.SystemCollectionsGeneric + ".IEnumerable";
	private const string ReadOnlyDictionaryTypeName = NamespaceNames.SystemCollectionsGeneric + ".IReadOnlyDictionary";
	private const string KeyValuePairTypeName = NamespaceNames.SystemCollectionsGeneric + ".KeyValuePair";

	private static readonly (string MetadataName, string FullName, string ShortName) AttributeNames =
		GeneratorHelpers.GetAttributeNames<GenerateEqualityAttribute>();

	/// <summary>
	/// Describes how a property is compared and hashed in the generated members.
	/// </summary>
	private enum EqualityStrategy
	{
		/// <summary>Compared with <c>Equals(left, right)</c>.</summary>
		Direct,
		/// <summary>Compared element-wise as a sequence.</summary>
		Sequence,
		/// <summary>A nullable <c>ImmutableArray&lt;T&gt;</c>, compared element-wise after conversion to a sequence.</summary>
		NullableImmutableArray,
		/// <summary>Compared key/value-wise as a dictionary.</summary>
		Dictionary
	}

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, AttributeNames.MetadataName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		bool includeInherited = GetIncludeInherited(ctx.ClassDeclaration, ctx.SemanticModel);
		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(ctx.ClassDeclaration, ctx.SemanticModel, nameof(GenerateEqualityAttribute));
		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, excludedProperties, detectCollections: true, includeInherited: includeInherited);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.EqualityGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, properties);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = GeneratorHelpers.BuildHintName(ctx.OuterClasses, ctx.ClassName, "Equality");

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.OpenClass(accessibility, className, $"IEquatable<{className}>");

		AppendEqualsObject(sb, className);
		sb.AppendLine();
		AppendEqualsT(sb, className, properties);
		sb.AppendLine();
		AppendGetHashCode(sb, properties);
		sb.AppendLine();
		AppendOperatorEquals(sb, className);
		sb.AppendLine();
		AppendOperatorNotEquals(sb, className);

		if (properties.Any(static p => GetStrategy(p) is EqualityStrategy.Sequence or EqualityStrategy.NullableImmutableArray))
			AppendSequenceHelpers(sb);

		if (properties.Any(static p => GetStrategy(p) is EqualityStrategy.Dictionary))
			AppendDictionaryHelpers(sb);

		sb.CloseClass();
	}

	/// <summary>
	/// Determines how the given property is compared and hashed.
	/// A non-nullable <c>ImmutableArray&lt;T&gt;</c> converts implicitly to a sequence, while a
	/// nullable one (<see cref="PropertyDescriptor.IsValueType"/> is <see langword="false"/>) does not.
	/// </summary>
	private static EqualityStrategy GetStrategy(PropertyDescriptor property) => property.CollectionKind switch
	{
		CollectionKind.Dictionary => EqualityStrategy.Dictionary,
		CollectionKind.ImmutableArray when !property.IsValueType => EqualityStrategy.NullableImmutableArray,
		CollectionKind.List or CollectionKind.Array or CollectionKind.ImmutableArray or CollectionKind.ReadOnlyCollection => EqualityStrategy.Sequence,
		_ => EqualityStrategy.Direct
	};

	private static void AppendEqualsObject(SourceBuilder sb, string className)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public override bool Equals(object? obj)");
		sb.Indent();
		sb.AppendLine($"=> Equals(obj as {className});");
		sb.Outdent();
	}

	private static void AppendEqualsT(SourceBuilder sb, string className, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine($"public bool Equals({className}? other)");
		sb.OpenBrace();
		sb.AppendLine("if (other is null)");
		sb.Indent();
		sb.AppendLine("return false;");
		sb.Outdent();
		sb.AppendLine();
		sb.AppendLine("if (ReferenceEquals(this, other))");
		sb.Indent();
		sb.AppendLine("return true;");
		sb.Outdent();

		if (properties.Length > 0)
		{
			sb.AppendLine();

			StringBuilder returnExpr = new();
			returnExpr.Append("return ");

			for (int i = 0; i < properties.Length; i++)
			{
				if (i > 0)
					returnExpr.Append("\n" + new string(' ', (sb.IndentLevel + 1) * 2) + "&& ");

				returnExpr.Append(BuildEqualsExpression(properties[i]));
			}

			returnExpr.Append(';');
			sb.AppendLine(returnExpr.ToString());
		}
		else
		{
			sb.AppendLine();
			sb.AppendLine("return true;");
		}

		sb.CloseBrace();
	}

	private static void AppendGetHashCode(SourceBuilder sb, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public override int GetHashCode()");
		sb.OpenBrace();

		if (properties.Length == 0)
		{
			sb.AppendLine("return base.GetHashCode();");
		}
		else
		{
			sb.AppendLine("unchecked");
			sb.OpenBrace();
			sb.AppendLine($"int hash = {HashSeed};");

			foreach (PropertyDescriptor property in properties)
				sb.AppendLine($"hash = hash * {HashFactor} + {BuildHashCodeExpression(property)};");

			sb.AppendLine("return hash;");
			sb.CloseBrace();
		}

		sb.CloseBrace();
	}

	private static void AppendOperatorEquals(SourceBuilder sb, string className)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Determines whether two <see cref=\"{className}\"/> instances are equal.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"public static bool operator ==({className}? left, {className}? right)");
		sb.Indent();
		sb.AppendLine("=> Equals(left, right);");
		sb.Outdent();
	}

	private static void AppendOperatorNotEquals(SourceBuilder sb, string className)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Determines whether two <see cref=\"{className}\"/> instances are not equal.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"public static bool operator !=({className}? left, {className}? right)");
		sb.Indent();
		sb.AppendLine("=> !Equals(left, right);");
		sb.Outdent();
	}

	private static string BuildEqualsExpression(PropertyDescriptor property) => GetStrategy(property) switch
	{
		EqualityStrategy.Dictionary => $"DictionaryEquals({property.Name}, other.{property.Name})",
		EqualityStrategy.Sequence => $"CollectionEquals({property.Name}, other.{property.Name})",
		EqualityStrategy.NullableImmutableArray => $"CollectionEquals({NullableImmutableArrayAsSequence(property, string.Empty)}, {NullableImmutableArrayAsSequence(property, "other.")})",
		_ => $"Equals({property.Name}, other.{property.Name})"
	};

	private static string BuildHashCodeExpression(PropertyDescriptor property) => GetStrategy(property) switch
	{
		EqualityStrategy.Dictionary => $"DictionaryHashCode({property.Name})",
		EqualityStrategy.Sequence => $"CollectionHashCode({property.Name})",
		EqualityStrategy.NullableImmutableArray => $"CollectionHashCode({NullableImmutableArrayAsSequence(property, string.Empty)})",
		_ => property.IsValueType
			? $"{property.Name}.GetHashCode()"
			: $"({property.Name}?.GetHashCode() ?? 0)"
	};

	private static string NullableImmutableArrayAsSequence(PropertyDescriptor property, string prefix)
		=> $"({prefix}{property.Name}.HasValue ? ({EnumerableTypeName}<{property.ElementTypeName}>){prefix}{property.Name}.Value : null)";

	private static void AppendSequenceHelpers(SourceBuilder sb)
	{
		sb.AppendLine();
		sb.AppendLine($"private static bool CollectionEquals<T>({EnumerableTypeName}<T>? left, {EnumerableTypeName}<T>? right)");
		sb.OpenBrace();
		sb.AppendLine("if (ReferenceEquals(left, right))");
		sb.Indent();
		sb.AppendLine("return true;");
		sb.Outdent();
		sb.AppendLine("if (left is null || right is null)");
		sb.Indent();
		sb.AppendLine("return false;");
		sb.Outdent();
		sb.AppendLine($"return {NamespaceNames.SystemLinq}.Enumerable.SequenceEqual(left, right);");
		sb.CloseBrace();

		sb.AppendLine();
		sb.AppendLine($"private static int CollectionHashCode<T>({EnumerableTypeName}<T>? sequence)");
		sb.OpenBrace();
		sb.AppendLine("if (sequence is null)");
		sb.Indent();
		sb.AppendLine("return 0;");
		sb.Outdent();
		sb.AppendLine("unchecked");
		sb.OpenBrace();
		sb.AppendLine($"int hash = {HashSeed};");
		sb.AppendLine("foreach (T item in sequence)");
		sb.Indent();
		sb.AppendLine($"hash = hash * {HashFactor} + (item?.GetHashCode() ?? 0);");
		sb.Outdent();
		sb.AppendLine("return hash;");
		sb.CloseBrace();
		sb.CloseBrace();
	}

	private static void AppendDictionaryHelpers(SourceBuilder sb)
	{
		sb.AppendLine();
		sb.AppendLine($"private static bool DictionaryEquals<TKey, TValue>({ReadOnlyDictionaryTypeName}<TKey, TValue>? left, {ReadOnlyDictionaryTypeName}<TKey, TValue>? right)");
		sb.OpenBrace();
		sb.AppendLine("if (ReferenceEquals(left, right))");
		sb.Indent();
		sb.AppendLine("return true;");
		sb.Outdent();
		sb.AppendLine("if (left is null || right is null || left.Count != right.Count)");
		sb.Indent();
		sb.AppendLine("return false;");
		sb.Outdent();
		sb.AppendLine($"foreach ({KeyValuePairTypeName}<TKey, TValue> pair in left)");
		sb.OpenBrace();
		sb.AppendLine("if (!right.ContainsKey(pair.Key) || !Equals(pair.Value, right[pair.Key]))");
		sb.Indent();
		sb.AppendLine("return false;");
		sb.Outdent();
		sb.CloseBrace();
		sb.AppendLine("return true;");
		sb.CloseBrace();

		sb.AppendLine();
		sb.AppendLine($"private static int DictionaryHashCode<TKey, TValue>({ReadOnlyDictionaryTypeName}<TKey, TValue>? dictionary)");
		sb.OpenBrace();
		sb.AppendLine("if (dictionary is null)");
		sb.Indent();
		sb.AppendLine("return 0;");
		sb.Outdent();
		sb.AppendLine("unchecked");
		sb.OpenBrace();
		// Order-independent: entry hashes are combined with XOR, so the seed must be 0.
		sb.AppendLine("int hash = 0;");
		sb.AppendLine($"foreach ({KeyValuePairTypeName}<TKey, TValue> pair in dictionary)");
		sb.Indent();
		sb.AppendLine($"hash ^= (pair.Key?.GetHashCode() ?? 0) * {HashFactor} + (pair.Value?.GetHashCode() ?? 0);");
		sb.Outdent();
		sb.AppendLine("return hash;");
		sb.CloseBrace();
		sb.CloseBrace();
	}

	private static bool GetIncludeInherited(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
		=> GeneratorHelpers.GetNamedArgumentValue(classDeclaration, semanticModel, AttributeNames.ShortName, AttributeNames.FullName, nameof(GenerateEqualityAttribute.IncludeInherited), false);
}
