// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating static <c>Read</c> and <c>Write</c> methods for classes marked
/// with the <see cref="GenerateIniFileAttribute"/> attribute. The generated methods support
/// serialization and deserialization of INI file content based on properties decorated with
/// <see cref="GenerateIniFileSectionAttribute"/> and <see cref="GenerateIniFileValueAttribute"/>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class IniFileGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorAttributeName = typeof(GenerateIniFileAttribute).FullName;
	private static readonly string SectionAttributeName = typeof(GenerateIniFileSectionAttribute).FullName;
	private static readonly string ValueAttributeName = typeof(GenerateIniFileValueAttribute).FullName;
	private const string AttributeFullName = nameof(GenerateIniFileAttribute);
	private static readonly string AttributeShortName = GeneratorHelpers.StripAttributeSuffix(AttributeFullName);
	private static readonly string[] LineBreakSeparators = ["\r\n", "\n"];

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		string stringComparison = GetStringComparison(ctx.ClassDeclaration, ctx.SemanticModel);
		string sectionDelimiter = GetSectionDelimiter(ctx.ClassDeclaration, ctx.SemanticModel);
		bool serializeComments = GetSerializeComments(ctx.ClassDeclaration);

		List<SectionInfo> sections = GetSections(ctx.ClassDeclaration, ctx.SemanticModel, sectionDelimiter, serializeComments);

		if (!ValidateSectionProperties(context, ctx.ClassDeclaration, ctx.SemanticModel))
			return;

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.IniFileGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendUsing(NamespaceNames.SystemCollectionsGeneric);
		sb.AppendUsing(NamespaceNames.SystemGlobalization);
		sb.AppendUsing(NamespaceNames.SystemIO);
		sb.AppendUsing(NamespaceNames.SystemLinq);
		sb.AppendUsing(NamespaceNames.SystemText);
		sb.AppendUsing(NamespaceNames.SystemThreading);
		sb.AppendUsing(NamespaceNames.SystemThreadingTasks);
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendReadMethod(sb, ctx.ClassName, ctx.Accessibility, sections, stringComparison);
		AppendTryReadMethod(sb, ctx.ClassName);
		AppendWriteMethod(sb, ctx.ClassName, sections, serializeComments);
		AppendReadAsyncMethod(sb, ctx.ClassName);
		AppendWriteAsyncMethod(sb, ctx.ClassName);
		AppendLoadMethod(sb, ctx.ClassName, sections);

		sb.CloseClass();
		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.g.cs"
			: $"{ctx.ClassName}.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendReadMethod(SourceBuilder sb, string className, string accessibility, List<SectionInfo> sections, string stringComparison)
	{
		sb.OpenClass(accessibility, className);
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Reads the specified INI file content and deserializes it into a new instance");
		sb.AppendLine($"/// of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"content\">The INI file string content to deserialize.</param>");
		sb.AppendLine($"/// <returns>A new instance of <see cref=\"{className}\"/> populated from the INI content.</returns>");
		sb.AppendLine($"public static {className} Read(string content)");
		sb.OpenBrace();
		sb.AppendLine($"{className} result = new {className}();");
		sb.AppendLine("string? currentSection = null;");
		sb.AppendLine("string[] lines = content.Split(new[] { \"\\r\\n\", \"\\n\" }, StringSplitOptions.None);");
		sb.AppendLine();
		sb.AppendLine("for (int i = 0; i < lines.Length; i++)");
		sb.OpenBrace();
		sb.AppendLine("string line = lines[i].Trim();");
		sb.AppendLine();
		sb.AppendLine("if (line.Length == 0 || line[0] == ';' || line[0] == '#')");
		sb.Indent();
		sb.AppendLine("continue;");
		sb.Outdent();
		sb.AppendLine();
		sb.AppendLine("if (line[0] == '[' && line[line.Length - 1] == ']')");
		sb.OpenBrace();
		sb.AppendLine("currentSection = line.Substring(1, line.Length - 2).Trim();");
		sb.AppendLine("continue;");
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("int equalsIndex = line.IndexOf('=');");
		sb.AppendLine("if (equalsIndex < 0)");
		sb.Indent();
		sb.AppendLine("continue;");
		sb.Outdent();
		sb.AppendLine();
		sb.AppendLine("string key = line.Substring(0, equalsIndex).Trim();");
		sb.AppendLine("string value = line.Substring(equalsIndex + 1).Trim();");
		sb.AppendLine();

		for (int s = 0; s < sections.Count; s++)
		{
			SectionInfo section = sections[s];
			string elsePrefix = s > 0 ? "else " : "";

			sb.AppendLine($"{elsePrefix}if (string.Equals(currentSection, \"{section.SectionName}\", StringComparison.{stringComparison}))");
			sb.OpenBrace();

			for (int v = 0; v < section.Values.Count; v++)
			{
				ValueInfo value = section.Values[v];
				string valueElsePrefix = v > 0 ? "else " : "";

				sb.AppendLine($"{valueElsePrefix}if (string.Equals(key, \"{value.KeyName}\", StringComparison.{stringComparison}))");
				sb.Indent();
				sb.AppendLine($"result.{section.PropertyPath}.{value.PropertyName} = {GetParseExpression(value, "value")};");
				sb.Outdent();
			}

			sb.CloseBrace();
		}

		sb.AppendLine();
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("return result;");
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendTryReadMethod(SourceBuilder sb, string className)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Tries to read the specified INI file content and deserialize it into a new instance");
		sb.AppendLine($"/// of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"content\">The INI file string content to deserialize.</param>");
		sb.AppendLine($"/// <param name=\"result\">When this method returns, contains the deserialized <see cref=\"{className}\"/> instance, or <c>null</c> if parsing failed.</param>");
		sb.AppendLine("/// <returns><c>true</c> if the content was successfully parsed; otherwise, <c>false</c>.</returns>");
		sb.AppendLine($"public static bool TryRead(string content, out {className}? result)");
		sb.OpenBrace();
		sb.AppendLine("try");
		sb.OpenBrace();
		sb.AppendLine("result = Read(content);");
		sb.AppendLine("return true;");
		sb.CloseBrace();
		sb.AppendLine("catch");
		sb.OpenBrace();
		sb.AppendLine("result = null;");
		sb.AppendLine("return false;");
		sb.CloseBrace();
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendWriteMethod(SourceBuilder sb, string className, List<SectionInfo> sections, bool serializeComments)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Writes the specified <see cref=\"{className}\"/> instance to an INI file string.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"instance\">The <see cref=\"{className}\"/> instance to serialize.</param>");
		sb.AppendLine("/// <returns>The serialized INI file string content.</returns>");
		sb.AppendLine($"public static string Write({className} instance)");
		sb.OpenBrace();
		sb.AppendLine("StringBuilder sb = new StringBuilder();");
		sb.AppendLine();

		for (int s = 0; s < sections.Count; s++)
		{
			SectionInfo section = sections[s];

			if (s > 0)
				sb.AppendLine("sb.AppendLine();");

			if (serializeComments && section.Comment is not null)
				sb.AppendLine($"sb.AppendLine(\"; {GeneratorHelpers.EscapeString(section.Comment)}\");");

			sb.AppendLine($"sb.AppendLine(\"[{section.SectionName}]\");");

			foreach (ValueInfo value in section.Values)
			{
				if (serializeComments && value.Comment is not null)
					sb.AppendLine($"sb.AppendLine(\"; {GeneratorHelpers.EscapeString(value.Comment)}\");");

				sb.AppendLine($"sb.AppendLine(\"{value.KeyName}=\" + {GetToStringExpression($"instance.{section.PropertyPath}.{value.PropertyName}", value)});");
			}
		}

		sb.AppendLine();
		sb.AppendLine("return sb.ToString();");
		sb.CloseBrace();
	}

	private static void AppendReadAsyncMethod(SourceBuilder sb, string className)
	{
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously reads INI file content from the specified <see cref=\"TextReader\"/> and deserializes it");
		sb.AppendLine($"/// into a new instance of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"reader\">The <see cref=\"TextReader\"/> to read from.</param>");
		sb.AppendLine("/// <param name=\"cancellationToken\">A cancellation token that can be used to cancel the asynchronous operation.</param>");
		sb.AppendLine($"/// <returns>A task representing the asynchronous operation, containing the deserialized <see cref=\"{className}\"/> instance.</returns>");
		sb.AppendLine($"public static async Task<{className}> ReadAsync(TextReader reader, CancellationToken cancellationToken = default)");
		sb.OpenBrace();
		sb.AppendLine("string content = await reader.ReadToEndAsync(cancellationToken).ConfigureAwait(false);");
		sb.AppendLine("return Read(content);");
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously reads INI file content from the specified <see cref=\"Stream\"/> and deserializes it");
		sb.AppendLine($"/// into a new instance of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"stream\">The <see cref=\"Stream\"/> to read from.</param>");
		sb.AppendLine("/// <param name=\"cancellationToken\">A cancellation token that can be used to cancel the asynchronous operation.</param>");
		sb.AppendLine($"/// <returns>A task representing the asynchronous operation, containing the deserialized <see cref=\"{className}\"/> instance.</returns>");
		sb.AppendLine($"public static async Task<{className}> ReadAsync(Stream stream, CancellationToken cancellationToken = default)");
		sb.OpenBrace();
		sb.AppendLine("using StreamReader reader = new StreamReader(stream, Encoding.UTF8, true, 1024, leaveOpen: true);");
		sb.AppendLine("return await ReadAsync(reader, cancellationToken).ConfigureAwait(false);");
		sb.CloseBrace();
	}

	private static void AppendWriteAsyncMethod(SourceBuilder sb, string className)
	{
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously writes the specified <see cref=\"{className}\"/> instance to the specified <see cref=\"TextWriter\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"instance\">The <see cref=\"{className}\"/> instance to serialize.</param>");
		sb.AppendLine("/// <param name=\"writer\">The <see cref=\"TextWriter\"/> to write to.</param>");
		sb.AppendLine("/// <param name=\"cancellationToken\">A cancellation token that can be used to cancel the asynchronous operation.</param>");
		sb.AppendLine("/// <returns>A task representing the asynchronous operation.</returns>");
		sb.AppendLine($"public static async Task WriteAsync({className} instance, TextWriter writer, CancellationToken cancellationToken = default)");
		sb.OpenBrace();
		sb.AppendLine("string content = Write(instance);");
		sb.AppendLine("StringBuilder builder = new StringBuilder(content);");
		sb.AppendLine("await writer.WriteAsync(builder, cancellationToken).ConfigureAwait(false);");
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously writes the specified <see cref=\"{className}\"/> instance to the specified <see cref=\"Stream\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"instance\">The <see cref=\"{className}\"/> instance to serialize.</param>");
		sb.AppendLine("/// <param name=\"stream\">The <see cref=\"Stream\"/> to write to.</param>");
		sb.AppendLine("/// <param name=\"cancellationToken\">A cancellation token that can be used to cancel the asynchronous operation.</param>");
		sb.AppendLine("/// <returns>A task representing the asynchronous operation.</returns>");
		sb.AppendLine($"public static async Task WriteAsync({className} instance, Stream stream, CancellationToken cancellationToken = default)");
		sb.OpenBrace();
		sb.AppendLine("using StreamWriter writer = new StreamWriter(stream, Encoding.UTF8, 1024, leaveOpen: true);");
		sb.AppendLine("await WriteAsync(instance, writer, cancellationToken).ConfigureAwait(false);");
		sb.CloseBrace();
	}

	private static void AppendLoadMethod(SourceBuilder sb, string className, List<SectionInfo> sections)
	{
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Loads values from the specified <paramref name=\"other\"/> instance into this instance.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"other\">The source <see cref=\"{className}\"/> instance to copy values from.</param>");
		sb.AppendLine($"public void Load({className} other)");
		sb.OpenBrace();

		foreach (SectionInfo section in sections)
		{
			foreach (ValueInfo value in section.Values)
				sb.AppendLine($"{section.PropertyPath}.{value.PropertyName} = other.{section.PropertyPath}.{value.PropertyName};");
		}

		sb.CloseBrace();
	}

	private static List<SectionInfo> GetSections(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel, string sectionDelimiter, bool serializeComments)
	{
		List<SectionInfo> sections = [];
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

		if (classSymbol is null)
			return sections;

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? sectionAttribute = FindAttribute(propertySymbol, SectionAttributeName);

			if (sectionAttribute is null)
				continue;

			if (propertySymbol.Type is not INamedTypeSymbol sectionType)
				continue;

			string sectionName = GetExplicitNameOrDefault(sectionAttribute, propertySymbol.Name);
			string propertyPath = propertySymbol.Name;
			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			List<ValueInfo> values = GetValues(sectionType, serializeComments);
			string sectionTypeName = GetNonNullableFullyQualifiedName(sectionType);

			sections.Add(new SectionInfo(
				PropertyName: propertySymbol.Name,
				PropertyPath: propertyPath,
				SectionName: sectionName,
				TypeName: sectionTypeName,
				Values: values,
				Comment: comment
			));

			CollectNestedSections(sections, sectionType, sectionName, propertyPath, sectionDelimiter, 1, serializeComments);
		}

		return sections;
	}

	private static void CollectNestedSections(List<SectionInfo> sections, INamedTypeSymbol parentType, string parentSectionName, string parentPropertyPath, string sectionDelimiter, int depth, bool serializeComments)
	{
		if (depth >= 8)
			return;

		foreach (ISymbol member in parentType.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? sectionAttribute = FindAttribute(propertySymbol, SectionAttributeName);

			if (sectionAttribute is null)
				continue;

			if (propertySymbol.Type is not INamedTypeSymbol sectionType)
				continue;

			string sectionName = GetExplicitNameOrDefault(sectionAttribute, propertySymbol.Name);
			string fullSectionName = $"{parentSectionName}{sectionDelimiter}{sectionName}";
			string propertyPath = $"{parentPropertyPath}.{propertySymbol.Name}";
			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			List<ValueInfo> values = GetValues(sectionType, serializeComments);
			string sectionTypeName = GetNonNullableFullyQualifiedName(sectionType);

			sections.Add(new SectionInfo(
				PropertyName: propertySymbol.Name,
				PropertyPath: propertyPath,
				SectionName: fullSectionName,
				TypeName: sectionTypeName,
				Values: values,
				Comment: comment
				));

			CollectNestedSections(sections, sectionType, fullSectionName, propertyPath, sectionDelimiter, depth + 1, serializeComments);
		}
	}

	private static List<ValueInfo> GetValues(INamedTypeSymbol sectionType, bool serializeComments = false)
	{
		List<ValueInfo> values = [];

		foreach (ISymbol member in sectionType.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? valueAttribute = FindAttribute(propertySymbol, ValueAttributeName);

			if (valueAttribute is null)
				continue;

			string keyName = GetExplicitNameOrDefault(valueAttribute, propertySymbol.Name);

			// Detect collection types (List<T> or T[])
			bool isCollection = false;
			string? collectionElementTypeName = null;

			if (propertySymbol.Type is IArrayTypeSymbol arrayType)
			{
				isCollection = true;
				collectionElementTypeName = GetSimpleTypeName(arrayType.ElementType);
			}
			else if (propertySymbol.Type is INamedTypeSymbol namedType
				&& namedType.IsGenericType
				&& namedType.ConstructedFrom.ToDisplayString().StartsWith("System.Collections.Generic.List", StringComparison.Ordinal)
				&& namedType.TypeArguments.Length == 1)
			{
				isCollection = true;
				collectionElementTypeName = GetSimpleTypeName(namedType.TypeArguments[0]);
			}

			string typeName = isCollection
				? propertySymbol.Type.ToDisplayString()
				: GetSimpleTypeName(propertySymbol.Type);

			bool isEnum = propertySymbol.Type.TypeKind == TypeKind.Enum;
			bool isFlagsEnum = false;
			string? enumFullName = null;

			if (isEnum)
			{
				enumFullName = propertySymbol.Type.ToFullyQualifiedDisplayString();
				isFlagsEnum = propertySymbol.Type.GetAttributes().Any(a => a.AttributeClass?.ToMinimalDisplayString() == "FlagsAttribute");
			}

			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			values.Add(new ValueInfo(
				PropertyName: propertySymbol.Name,
				KeyName: keyName,
				TypeName: typeName,
				IsEnum: isEnum,
				IsFlagsEnum: isFlagsEnum,
				EnumFullName: enumFullName,
				Comment: comment,
				IsCollection: isCollection,
				CollectionElementTypeName: collectionElementTypeName,
				IsArray: propertySymbol.Type is IArrayTypeSymbol
			));
		}

		return values;
	}

	private static bool HasInitializer(ClassDeclarationSyntax classDeclaration, string propertyName)
	{
		foreach (MemberDeclarationSyntax member in classDeclaration.Members)
		{
			if (member is PropertyDeclarationSyntax propSyntax && propSyntax.Identifier.Text == propertyName && propSyntax.Initializer is not null)
				return true;
		}

		return false;
	}

	private static bool HasInitializer(INamedTypeSymbol typeSymbol, string propertyName)
	{
		foreach (SyntaxReference syntaxRef in typeSymbol.DeclaringSyntaxReferences)
		{
			if (syntaxRef.GetSyntax() is ClassDeclarationSyntax classDeclaration && HasInitializer(classDeclaration, propertyName))
				return true;
		}

		return false;
	}

	private static string GetParseExpression(ValueInfo value, string variableName)
	{
		if (value.IsCollection && value.CollectionElementTypeName is not null)
		{
			string elementParse = GetElementParseExpression(value.CollectionElementTypeName, "e.Trim()");
			string selectExpr = $"{variableName}.Split(',').Select(e => {elementParse})";
			return value.IsArray
				? $"{selectExpr}.ToArray()"
				: $"{selectExpr}.ToList()";
		}

		return value.IsEnum && value.EnumFullName is not null
			? value.IsFlagsEnum
				? $"({value.EnumFullName}){variableName}.Split(' ').Select(flag => ({value.EnumFullName})Enum.Parse(typeof({value.EnumFullName}), flag)).Aggregate(0, (current, flag) => current | (int)flag)"
				: $"({value.EnumFullName})Enum.Parse(typeof({value.EnumFullName}), {variableName})"
			: GetElementParseExpression(value.TypeName, variableName);
	}

	private static string GetElementParseExpression(string elementTypeName, string variableName)
	{
		return elementTypeName switch
		{
			"string" => variableName,
			"int" => $"int.Parse({variableName}, CultureInfo.InvariantCulture)",
			"long" => $"long.Parse({variableName}, CultureInfo.InvariantCulture)",
			"float" => $"float.Parse({variableName}, CultureInfo.InvariantCulture)",
			"double" => $"double.Parse({variableName}, CultureInfo.InvariantCulture)",
			"bool" => $"bool.Parse({variableName})",
			"decimal" => $"decimal.Parse({variableName}, CultureInfo.InvariantCulture)",
			"DateTime" => $"DateTime.Parse({variableName}, CultureInfo.InvariantCulture)",
			"Guid" => $"Guid.Parse({variableName})",
			"TimeSpan" => $"TimeSpan.Parse({variableName}, CultureInfo.InvariantCulture)",
			"DateTimeOffset" => $"DateTimeOffset.Parse({variableName}, CultureInfo.InvariantCulture)",
			_ => variableName,
		};
	}

	private static string GetSimpleTypeName(ITypeSymbol type)
	{
		return type.SpecialType switch
		{
			SpecialType.System_String => "string",
			SpecialType.System_Int32 => "int",
			SpecialType.System_Int64 => "long",
			SpecialType.System_Single => "float",
			SpecialType.System_Double => "double",
			SpecialType.System_Boolean => "bool",
			SpecialType.System_Decimal => "decimal",
			SpecialType.System_DateTime => "DateTime",
			_ => type.ToMinimalDisplayString() switch
			{
				"Guid" => "Guid",
				"TimeSpan" => "TimeSpan",
				"DateTimeOffset" => "DateTimeOffset",
				var other => other
			}
		};
	}

	private static string GetToStringExpression(string expression, ValueInfo value)
	{
		if (value.IsCollection)
		{
			string elementToString = value.CollectionElementTypeName switch
			{
				"string" => "e",
				"bool" => "e.ToString()",
				"DateTime" or "TimeSpan" or "DateTimeOffset" => "e.ToString(CultureInfo.InvariantCulture)",
				"int" or "long" or "float" or "double" or "decimal" => "e.ToString(CultureInfo.InvariantCulture)",
				"Guid" => "e.ToString()",
				_ => "e?.ToString() ?? string.Empty"
			};

			string emptyFallback = value.IsArray
				? $"Array.Empty<{value.CollectionElementTypeName}>()"
				: $"Enumerable.Empty<{value.CollectionElementTypeName}>()";

			return $"string.Join(\",\", ({expression} ?? {emptyFallback}).Select(e => {elementToString}))";
		}

		return value.IsEnum && value.EnumFullName is not null
			? value.IsFlagsEnum
				? $"string.Join(\" \", Enum.GetValues(typeof({value.EnumFullName})).Cast<{value.EnumFullName}>().Where(flag => flag != 0 && {expression}.HasFlag(flag)).Select(flag => flag.ToString()))"
				: $"{expression}.ToString()"
			: value.TypeName switch
			{
				"string" => expression,
				"bool" => $"{expression}.ToString()",
				"DateTime" or "DateTimeOffset" => $"{expression}.ToString(CultureInfo.InvariantCulture)",
				"TimeSpan" => $"{expression}.ToString(\"c\", CultureInfo.InvariantCulture)",
				"Guid" => $"{expression}.ToString()",
				"int" or "long" or "float" or "double" or "decimal" =>
					$"{expression}.ToString(CultureInfo.InvariantCulture)",
				_ => $"{expression}?.ToString() ?? string.Empty",
			};
	}

	private static string GetStringComparison(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

		if (classSymbol is null)
			return nameof(StringComparison.OrdinalIgnoreCase);

		AttributeData? attributeData = FindGeneratorAttribute(classSymbol);

		return attributeData is not null
			&& attributeData.ConstructorArguments.Length > 0
			&& attributeData.ConstructorArguments[0].Value is int comparisonValue
				? comparisonValue switch
				{
					0 => nameof(StringComparison.CurrentCulture),
					1 => nameof(StringComparison.CurrentCultureIgnoreCase),
					2 => nameof(StringComparison.InvariantCulture),
					3 => nameof(StringComparison.InvariantCultureIgnoreCase),
					4 => nameof(StringComparison.Ordinal),
					5 => nameof(StringComparison.OrdinalIgnoreCase),
					_ => nameof(StringComparison.OrdinalIgnoreCase)
				}
				: nameof(StringComparison.OrdinalIgnoreCase);
	}

	private static string GetSectionDelimiter(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return ".";

		AttributeData? attributeData = FindGeneratorAttribute(classSymbol);

		return attributeData is not null
			&& attributeData.ConstructorArguments.Length > 1
			&& attributeData.ConstructorArguments[1].Value is string delimiterValue
				? delimiterValue
				: ".";
	}

	private static bool GetSerializeComments(ClassDeclarationSyntax classDeclaration)
	{
		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != AttributeShortName && name != AttributeFullName)
					continue;

				if (attribute.ArgumentList is null)
					continue;

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					if (argument.NameEquals?.Name.Identifier.Text == "SerializeComments")
					{
						string expressionText = argument.Expression.ToString();
						if (expressionText == "true")
							return true;
					}
				}
			}
		}

		return false;
	}

	private static string? GetXmlSummaryComment(ISymbol symbol)
	{
		foreach (SyntaxReference syntaxRef in symbol.DeclaringSyntaxReferences)
		{
			SyntaxNode node = syntaxRef.GetSyntax();

			if (!node.HasLeadingTrivia)
				continue;

			foreach (SyntaxTrivia trivia in node.GetLeadingTrivia())
			{
				if (trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia))
				{
					SyntaxNode? structure = trivia.GetStructure();
					if (structure is null)
						continue;

					foreach (SyntaxNode child in structure.ChildNodes())
					{
						if (child is not XmlElementSyntax xmlElement)
							continue;

						if (xmlElement.StartTag.Name.ToString() != "summary")
							continue;

						string content = xmlElement.Content.ToString();
						string[] lines = content.Split(LineBreakSeparators, StringSplitOptions.RemoveEmptyEntries);

						List<string> cleanLines = [];
						foreach (string line in lines)
						{
							string trimmed = line.Trim().TrimStart('/').Trim();
							if (trimmed.Length > 0)
								cleanLines.Add(trimmed);
						}

						if (cleanLines.Count > 0)
							return string.Join(" ", cleanLines);
					}
				}
			}
		}

		return null;
	}

	private static bool ValidateSectionProperties(SourceProductionContext context, ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

		if (classSymbol is null)
			return false;

		bool isValid = true;
		ValidateSectionPropertiesOnType(context, classSymbol, classDeclaration, ref isValid);
		return isValid;
	}

	private static void ValidateSectionPropertiesOnType(SourceProductionContext context, INamedTypeSymbol typeSymbol, ClassDeclarationSyntax? classDeclaration, ref bool isValid)
	{
		foreach (ISymbol member in typeSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? sectionAttribute = FindAttribute(propertySymbol, SectionAttributeName);

			if (sectionAttribute is null)
				continue;

			string className = typeSymbol.Name;
			Location location = propertySymbol.Locations.FirstOrDefault() ?? Location.None;

			// Check nullable
			if (propertySymbol.Type.NullableAnnotation == NullableAnnotation.Annotated)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					DiagnosticDescriptors.IniFileSectionNullablePropertyDiagnostic,
					location,
					propertySymbol.Name,
					className));
				isValid = false;
			}

			// Check initialized
			bool hasInit = classDeclaration is not null
				? HasInitializer(classDeclaration, propertySymbol.Name)
				: HasInitializer(typeSymbol, propertySymbol.Name);

			if (!hasInit)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					DiagnosticDescriptors.IniFileSectionUninitializedPropertyDiagnostic,
					location,
					propertySymbol.Name,
					className));
				isValid = false;
			}

			// Check public getter
			if (propertySymbol.GetMethod is null || propertySymbol.GetMethod.DeclaredAccessibility != Accessibility.Public)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					DiagnosticDescriptors.IniFileSectionNoPublicGetterDiagnostic,
					location,
					propertySymbol.Name,
					className));
				isValid = false;
			}

			// Recursively validate nested section types
			if (propertySymbol.Type is INamedTypeSymbol nestedType)
				ValidateSectionPropertiesOnType(context, nestedType, null, ref isValid);
		}
	}

	private static AttributeData? FindAttribute(IPropertySymbol propertySymbol, string attributeName)
	{
		foreach (AttributeData attr in propertySymbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == attributeName)
				return attr;
		}

		return null;
	}

	private static string GetExplicitNameOrDefault(AttributeData attribute, string defaultName)
	{
		return attribute.ConstructorArguments.Length > 0
			&& attribute.ConstructorArguments[0].Value is string explicitName
			&& !string.IsNullOrEmpty(explicitName)
			? explicitName
			: defaultName;
	}

	private static string GetNonNullableFullyQualifiedName(INamedTypeSymbol type)
	{
		string typeName = type
			.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
			.ToFullyQualifiedDisplayString();

		if (typeName.EndsWith("?", StringComparison.Ordinal))
			typeName = typeName[..^1];

		return typeName;
	}

	private static AttributeData? FindGeneratorAttribute(INamedTypeSymbol classSymbol)
	{
		foreach (AttributeData attr in classSymbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == GeneratorAttributeName)
				return attr;
		}

		return null;
	}

	private sealed record SectionInfo(
		string PropertyName,
		string PropertyPath,
		string SectionName,
		string TypeName,
		List<ValueInfo> Values,
		string? Comment = null
	);

	private sealed record ValueInfo(
		string PropertyName,
		string KeyName,
		string TypeName,
		bool IsEnum = false,
		bool IsFlagsEnum = false,
		string? EnumFullName = null,
		string? Comment = null,
		bool IsCollection = false,
		string? CollectionElementTypeName = null,
		bool IsArray = false
	);
}
