// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating static <c>Read</c> and <c>Write</c> methods for classes marked
/// with the <see cref="GenerateIniFileAttribute"/> attribute. The generated methods support
/// serialization and deserialization of INI file content based on properties decorated with
/// <see cref="GenerateIniFileSectionAttribute"/> and <see cref="GenerateIniFileValueAttribute"/>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class IniFileGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(IniFileGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateIniFileAttribute).FullName;
	private static readonly string SectionAttributeName = typeof(GenerateIniFileSectionAttribute).FullName;
	private static readonly string ValueAttributeName = typeof(GenerateIniFileValueAttribute).FullName;
	private const string AttributeFullName = nameof(GenerateIniFileAttribute);
	private static readonly string AttributeShortName = GeneratorHelpers.StripAttributeSuffix(AttributeFullName);
	private static readonly string[] LineBreakSeparators = ["\r\n", "\n"];

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		string stringComparison = GetStringComparison(ctx.ClassDeclaration, ctx.SemanticModel);
		string sectionDelimiter = GetSectionDelimiter(ctx.ClassDeclaration, ctx.SemanticModel);
		bool serializeComments = GetSerializeComments(ctx.ClassDeclaration);

		List<SectionInfo> sections = GetSections(ctx.ClassDeclaration, ctx.SemanticModel, sectionDelimiter, serializeComments);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendNullableEnable();
		sb.AppendUsing("System");
		sb.AppendUsing("System.Collections.Generic");
		sb.AppendUsing("System.Globalization");
		sb.AppendUsing("System.IO");
		sb.AppendUsing("System.Linq");
		sb.AppendUsing("System.Text");
		sb.AppendUsing("System.Threading.Tasks");
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendReadMethod(sb, ctx.ClassName, ctx.Accessibility, sections, stringComparison);
		AppendTryReadMethod(sb, ctx.ClassName, sections, stringComparison);
		AppendWriteMethod(sb, ctx.ClassName, sections, serializeComments);
		AppendReadAsyncMethod(sb, ctx.ClassName);
		AppendWriteAsyncMethod(sb, ctx.ClassName);
		AppendLoadMethod(sb, ctx.ClassName, sections);

		sb.CloseClass();
		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.g.cs"
			: $"{ctx.ClassName}.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendReadMethod(SourceBuilder sb, string className, string accessibility, List<SectionInfo> sections, string stringComparison)
	{
		sb.OpenClass(accessibility, className);
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Reads the specified INI file content and deserializes it into a new instance");
		sb.AppendLine($"/// of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"content\">The INI file string content to deserialize.</param>");
		sb.AppendLine($"/// <returns>A new instance of <see cref=\"{className}\"/> populated from the INI content.</returns>");
		sb.AppendLine($"public static {className} Read(string content)");
		sb.OpenBrace();
		sb.AppendLine($"{className} result = new {className}();");
		sb.AppendLine("string? currentSection = null;");
		sb.AppendLine("string[] lines = content.Split(new[] { \"\\r\\n\", \"\\n\" }, StringSplitOptions.None);");
		sb.AppendLine();
		sb.AppendLine("for (int i = 0; i < lines.Length; i++)");
		sb.OpenBrace();
		sb.AppendLine("string line = lines[i].Trim();");
		sb.AppendLine();
		sb.AppendLine("if (line.Length == 0 || line[0] == ';' || line[0] == '#')");
		sb.Indent();
		sb.AppendLine("continue;");
		sb.Outdent();
		sb.AppendLine();
		sb.AppendLine("if (line[0] == '[' && line[line.Length - 1] == ']')");
		sb.OpenBrace();
		sb.AppendLine("currentSection = line.Substring(1, line.Length - 2).Trim();");
		sb.AppendLine("continue;");
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("int equalsIndex = line.IndexOf('=');");
		sb.AppendLine("if (equalsIndex < 0)");
		sb.Indent();
		sb.AppendLine("continue;");
		sb.Outdent();
		sb.AppendLine();
		sb.AppendLine("string key = line.Substring(0, equalsIndex).Trim();");
		sb.AppendLine("string value = line.Substring(equalsIndex + 1).Trim();");
		sb.AppendLine();

		for (int s = 0; s < sections.Count; s++)
		{
			SectionInfo section = sections[s];
			string elsePrefix = s > 0 ? "else " : "";

			sb.AppendLine($"{elsePrefix}if (string.Equals(currentSection, \"{section.SectionName}\", StringComparison.{stringComparison}))");
			sb.OpenBrace();

			if (section.NeedsInitialization)
			{
				sb.AppendLine($"if (result.{section.PropertyPath} == null)");
				sb.Indent();
				sb.AppendLine($"result.{section.PropertyPath} = new {section.TypeName}();");
				sb.Outdent();
				sb.AppendLine();
			}

			for (int v = 0; v < section.Values.Count; v++)
			{
				ValueInfo value = section.Values[v];
				string valueElsePrefix = v > 0 ? "else " : "";

				sb.AppendLine($"{valueElsePrefix}if (string.Equals(key, \"{value.KeyName}\", StringComparison.{stringComparison}))");
				sb.Indent();
				sb.AppendLine($"result.{section.PropertyPath}.{value.PropertyName} = {GetParseExpression(value, "value")};");
				sb.Outdent();
			}

			sb.CloseBrace();
		}

		sb.AppendLine();
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("return result;");
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendTryReadMethod(SourceBuilder sb, string className, List<SectionInfo> sections, string stringComparison)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Tries to read the specified INI file content and deserialize it into a new instance");
		sb.AppendLine($"/// of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"content\">The INI file string content to deserialize.</param>");
		sb.AppendLine($"/// <param name=\"result\">When this method returns, contains the deserialized <see cref=\"{className}\"/> instance, or <c>null</c> if parsing failed.</param>");
		sb.AppendLine("/// <returns><c>true</c> if the content was successfully parsed; otherwise, <c>false</c>.</returns>");
		sb.AppendLine($"public static bool TryRead(string content, out {className}? result)");
		sb.OpenBrace();
		sb.AppendLine("try");
		sb.OpenBrace();
		sb.AppendLine("result = Read(content);");
		sb.AppendLine("return true;");
		sb.CloseBrace();
		sb.AppendLine("catch");
		sb.OpenBrace();
		sb.AppendLine("result = null;");
		sb.AppendLine("return false;");
		sb.CloseBrace();
		sb.CloseBrace();
		sb.AppendLine();
	}

	private static void AppendWriteMethod(SourceBuilder sb, string className, List<SectionInfo> sections, bool serializeComments)
	{
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Writes the specified <see cref=\"{className}\"/> instance to an INI file string.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"instance\">The <see cref=\"{className}\"/> instance to serialize.</param>");
		sb.AppendLine("/// <returns>The serialized INI file string content.</returns>");
		sb.AppendLine($"public static string Write({className} instance)");
		sb.OpenBrace();
		sb.AppendLine("StringBuilder sb = new StringBuilder();");
		sb.AppendLine();

		for (int s = 0; s < sections.Count; s++)
		{
			SectionInfo section = sections[s];

			if (s > 0)
				sb.AppendLine("sb.AppendLine();");

			string nullCheck = BuildNullCheck($"instance.{section.PropertyPath}");
			sb.AppendLine($"if ({nullCheck})");
			sb.OpenBrace();

			if (serializeComments && section.Comment is not null)
				sb.AppendLine($"sb.AppendLine(\"; {GeneratorHelpers.EscapeString(section.Comment)}\");");

			sb.AppendLine($"sb.AppendLine(\"[{section.SectionName}]\");");

			foreach (ValueInfo value in section.Values)
			{
				if (serializeComments && value.Comment is not null)
					sb.AppendLine($"sb.AppendLine(\"; {GeneratorHelpers.EscapeString(value.Comment)}\");");

				sb.AppendLine($"sb.AppendLine(\"{value.KeyName}=\" + {GetToStringExpression($"instance.{section.PropertyPath}.{value.PropertyName}", value)});");
			}

			sb.CloseBrace();
		}

		sb.AppendLine();
		sb.AppendLine("return sb.ToString();");
		sb.CloseBrace();
	}

	private static void AppendReadAsyncMethod(SourceBuilder sb, string className)
	{
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously reads INI file content from the specified <see cref=\"TextReader\"/> and deserializes it");
		sb.AppendLine($"/// into a new instance of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"reader\">The <see cref=\"TextReader\"/> to read from.</param>");
		sb.AppendLine($"/// <returns>A task representing the asynchronous operation, containing the deserialized <see cref=\"{className}\"/> instance.</returns>");
		sb.AppendLine($"public static async Task<{className}> ReadAsync(TextReader reader)");
		sb.OpenBrace();
		sb.AppendLine("string content = await reader.ReadToEndAsync().ConfigureAwait(false);");
		sb.AppendLine("return Read(content);");
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously reads INI file content from the specified <see cref=\"Stream\"/> and deserializes it");
		sb.AppendLine($"/// into a new instance of <see cref=\"{className}\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"stream\">The <see cref=\"Stream\"/> to read from.</param>");
		sb.AppendLine($"/// <returns>A task representing the asynchronous operation, containing the deserialized <see cref=\"{className}\"/> instance.</returns>");
		sb.AppendLine($"public static async Task<{className}> ReadAsync(Stream stream)");
		sb.OpenBrace();
		sb.AppendLine("using StreamReader reader = new StreamReader(stream, System.Text.Encoding.UTF8, true, 1024, leaveOpen: true);");
		sb.AppendLine("return await ReadAsync(reader).ConfigureAwait(false);");
		sb.CloseBrace();
	}

	private static void AppendWriteAsyncMethod(SourceBuilder sb, string className)
	{
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously writes the specified <see cref=\"{className}\"/> instance to the specified <see cref=\"TextWriter\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"instance\">The <see cref=\"{className}\"/> instance to serialize.</param>");
		sb.AppendLine("/// <param name=\"writer\">The <see cref=\"TextWriter\"/> to write to.</param>");
		sb.AppendLine("/// <returns>A task representing the asynchronous operation.</returns>");
		sb.AppendLine($"public static async Task WriteAsync({className} instance, TextWriter writer)");
		sb.OpenBrace();
		sb.AppendLine("string content = Write(instance);");
		sb.AppendLine("await writer.WriteAsync(content).ConfigureAwait(false);");
		sb.CloseBrace();
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Asynchronously writes the specified <see cref=\"{className}\"/> instance to the specified <see cref=\"Stream\"/>.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"instance\">The <see cref=\"{className}\"/> instance to serialize.</param>");
		sb.AppendLine("/// <param name=\"stream\">The <see cref=\"Stream\"/> to write to.</param>");
		sb.AppendLine("/// <returns>A task representing the asynchronous operation.</returns>");
		sb.AppendLine($"public static async Task WriteAsync({className} instance, Stream stream)");
		sb.OpenBrace();
		sb.AppendLine("using StreamWriter writer = new StreamWriter(stream, System.Text.Encoding.UTF8, 1024, leaveOpen: true);");
		sb.AppendLine("await WriteAsync(instance, writer).ConfigureAwait(false);");
		sb.CloseBrace();
	}

	private static void AppendLoadMethod(SourceBuilder sb, string className, List<SectionInfo> sections)
	{
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine($"/// Loads values from the specified <paramref name=\"other\"/> instance into this instance.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"/// <param name=\"other\">The source <see cref=\"{className}\"/> instance to copy values from.</param>");
		sb.AppendLine($"public void Load({className} other)");
		sb.OpenBrace();

		foreach (SectionInfo section in sections)
		{
			string targetNullCheck = BuildNullCheck($"this.{section.PropertyPath}");
			string sourceNullCheck = BuildNullCheck($"other.{section.PropertyPath}");
			sb.AppendLine($"if ({targetNullCheck} && {sourceNullCheck})");
			sb.OpenBrace();

			foreach (ValueInfo value in section.Values)
				sb.AppendLine($"{section.PropertyPath}.{value.PropertyName} = other.{section.PropertyPath}.{value.PropertyName};");

			sb.CloseBrace();
		}

		sb.CloseBrace();
	}

	private static List<SectionInfo> GetSections(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel, string sectionDelimiter, bool serializeComments)
	{
		List<SectionInfo> sections = [];
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

		if (classSymbol is null)
			return sections;

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? sectionAttribute = null;
			foreach (AttributeData attr in propertySymbol.GetAttributes())
			{
				if (attr.AttributeClass?.ToDisplayString() == SectionAttributeName)
				{
					sectionAttribute = attr;
					break;
				}
			}

			if (sectionAttribute is null)
				continue;

			string sectionName = propertySymbol.Name;
			if (sectionAttribute.ConstructorArguments.Length > 0
				&& sectionAttribute.ConstructorArguments[0].Value is string explicitName
				&& !string.IsNullOrEmpty(explicitName))
			{
				sectionName = explicitName;
			}

			if (propertySymbol.Type is not INamedTypeSymbol sectionType)
				continue;

			bool needsInit = !HasInitializer(classDeclaration, propertySymbol.Name);
			string propertyPath = propertySymbol.Name;
			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			List<ValueInfo> values = GetValues(sectionType, serializeComments);

			string sectionTypeName = sectionType
				.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
				.ToFullyQualifiedDisplayString();

			if (sectionTypeName.EndsWith("?", StringComparison.Ordinal))
				sectionTypeName = sectionTypeName[..^1];

			sections.Add(new SectionInfo(
				PropertyName: propertySymbol.Name,
				PropertyPath: propertyPath,
				SectionName: sectionName,
				TypeName: sectionTypeName,
				NeedsInitialization: needsInit,
				Values: values,
				Comment: comment
			));

			CollectNestedSections(sections, sectionType, sectionName, propertyPath, sectionDelimiter, 1, serializeComments);
		}

		return sections;
	}

	private static void CollectNestedSections(List<SectionInfo> sections, INamedTypeSymbol parentType, string parentSectionName, string parentPropertyPath, string sectionDelimiter, int depth, bool serializeComments)
	{
		if (depth >= 8)
			return;

		foreach (ISymbol member in parentType.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? sectionAttribute = null;
			foreach (AttributeData attr in propertySymbol.GetAttributes())
			{
				if (attr.AttributeClass?.ToDisplayString() == SectionAttributeName)
				{
					sectionAttribute = attr;
					break;
				}
			}

			if (sectionAttribute is null)
				continue;

			string sectionName = propertySymbol.Name;
			if (sectionAttribute.ConstructorArguments.Length > 0
				&& sectionAttribute.ConstructorArguments[0].Value is string explicitName
				&& !string.IsNullOrEmpty(explicitName))
			{
				sectionName = explicitName;
			}

			if (propertySymbol.Type is not INamedTypeSymbol sectionType)
				continue;

			string fullSectionName = $"{parentSectionName}{sectionDelimiter}{sectionName}";
			string propertyPath = $"{parentPropertyPath}.{propertySymbol.Name}";
			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			List<ValueInfo> values = GetValues(sectionType, serializeComments);

			string sectionTypeName = sectionType
				 .WithNullableAnnotation(NullableAnnotation.NotAnnotated)
				 .ToFullyQualifiedDisplayString();

			if (sectionTypeName.EndsWith("?", StringComparison.Ordinal))
				sectionTypeName = sectionTypeName[..^1];

			sections.Add(new SectionInfo(
				PropertyName: propertySymbol.Name,
				PropertyPath: propertyPath,
				SectionName: fullSectionName,
				TypeName: sectionTypeName,
				NeedsInitialization: false,
				Values: values,
				Comment: comment
			));

			CollectNestedSections(sections, sectionType, fullSectionName, propertyPath, sectionDelimiter, depth + 1, serializeComments);
		}
	}

	private static List<ValueInfo> GetValues(INamedTypeSymbol sectionType, bool serializeComments = false)
	{
		List<ValueInfo> values = [];

		foreach (ISymbol member in sectionType.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? valueAttribute = null;
			foreach (AttributeData attr in propertySymbol.GetAttributes())
			{
				if (attr.AttributeClass?.ToDisplayString() == ValueAttributeName)
				{
					valueAttribute = attr;
					break;
				}
			}

			if (valueAttribute is null)
				continue;

			string keyName = propertySymbol.Name;
			if (valueAttribute.ConstructorArguments.Length > 0
				&& valueAttribute.ConstructorArguments[0].Value is string explicitName
				&& !string.IsNullOrEmpty(explicitName))
			{
				keyName = explicitName;
			}

			// Detect collection types (List<T> or T[])
			bool isCollection = false;
			string? collectionElementTypeName = null;

			if (propertySymbol.Type is IArrayTypeSymbol arrayType)
			{
				isCollection = true;
				collectionElementTypeName = GetSimpleTypeName(arrayType.ElementType);
			}
			else if (propertySymbol.Type is INamedTypeSymbol namedType
				&& namedType.IsGenericType
				&& namedType.ConstructedFrom.ToDisplayString().StartsWith("System.Collections.Generic.List", StringComparison.Ordinal)
				&& namedType.TypeArguments.Length == 1)
			{
				isCollection = true;
				collectionElementTypeName = GetSimpleTypeName(namedType.TypeArguments[0]);
			}

			string typeName = isCollection
				? propertySymbol.Type.ToDisplayString()
				: propertySymbol.Type.SpecialType switch
				{
					SpecialType.System_String => "string",
					SpecialType.System_Int32 => "int",
					SpecialType.System_Int64 => "long",
					SpecialType.System_Single => "float",
					SpecialType.System_Double => "double",
					SpecialType.System_Boolean => "bool",
					SpecialType.System_Decimal => "decimal",
					SpecialType.System_DateTime => "DateTime",
					_ => propertySymbol.Type.ToDisplayString() switch
					{
						"System.Guid" => "Guid",
						"System.TimeSpan" => "TimeSpan",
						"System.DateTimeOffset" => "DateTimeOffset",
						var other => other
					}
				};

			bool isEnum = propertySymbol.Type.TypeKind == TypeKind.Enum;
			bool isFlagsEnum = false;
			string? enumFullName = null;

			if (isEnum)
			{
				enumFullName = propertySymbol.Type.ToFullyQualifiedDisplayString();
				isFlagsEnum = propertySymbol.Type.GetAttributes()
					.Any(a => a.AttributeClass?.ToDisplayString() == "System.FlagsAttribute");
			}

			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			values.Add(new ValueInfo(
				PropertyName: propertySymbol.Name,
				KeyName: keyName,
				TypeName: typeName,
				IsEnum: isEnum,
				IsFlagsEnum: isFlagsEnum,
				EnumFullName: enumFullName,
				Comment: comment,
				IsCollection: isCollection,
				CollectionElementTypeName: collectionElementTypeName,
				IsArray: propertySymbol.Type is IArrayTypeSymbol
			));
		}

		return values;
	}

	private static bool HasInitializer(ClassDeclarationSyntax classDeclaration, string propertyName)
	{
		foreach (MemberDeclarationSyntax member in classDeclaration.Members)
		{
			if (member is PropertyDeclarationSyntax propSyntax
				&& propSyntax.Identifier.Text == propertyName
				&& propSyntax.Initializer is not null)
			{
				return true;
			}
		}

		return false;
	}

	private static string GetParseExpression(ValueInfo value, string variableName)
	{
		if (value.IsCollection && value.CollectionElementTypeName is not null)
		{
			string elementParse = GetElementParseExpression(value.CollectionElementTypeName, "e.Trim()");
			string selectExpr = $"{variableName}.Split(',').Select(e => {elementParse})";
			return value.IsArray
				? $"{selectExpr}.ToArray()"
				: $"{selectExpr}.ToList()";
		}

		return value.IsEnum && value.EnumFullName is not null
			? value.IsFlagsEnum
				? $"({value.EnumFullName}){variableName}.Split(' ').Select(flag => ({value.EnumFullName})Enum.Parse(typeof({value.EnumFullName}), flag)).Aggregate(0, (current, flag) => current | (int)flag)"
				: $"({value.EnumFullName})Enum.Parse(typeof({value.EnumFullName}), {variableName})"
			: value.TypeName switch
			{
				"string" => variableName,
				"int" => $"int.Parse({variableName}, CultureInfo.InvariantCulture)",
				"long" => $"long.Parse({variableName}, CultureInfo.InvariantCulture)",
				"float" => $"float.Parse({variableName}, CultureInfo.InvariantCulture)",
				"double" => $"double.Parse({variableName}, CultureInfo.InvariantCulture)",
				"bool" => $"bool.Parse({variableName})",
				"decimal" => $"decimal.Parse({variableName}, CultureInfo.InvariantCulture)",
				"DateTime" => $"DateTime.Parse({variableName}, CultureInfo.InvariantCulture)",
				"Guid" => $"Guid.Parse({variableName})",
				"TimeSpan" => $"TimeSpan.Parse({variableName}, CultureInfo.InvariantCulture)",
				"DateTimeOffset" => $"DateTimeOffset.Parse({variableName}, CultureInfo.InvariantCulture)",
				_ => variableName,
			};
	}

	private static string GetElementParseExpression(string elementTypeName, string variableName)
	{
		return elementTypeName switch
		{
			"string" => variableName,
			"int" => $"int.Parse({variableName}, CultureInfo.InvariantCulture)",
			"long" => $"long.Parse({variableName}, CultureInfo.InvariantCulture)",
			"float" => $"float.Parse({variableName}, CultureInfo.InvariantCulture)",
			"double" => $"double.Parse({variableName}, CultureInfo.InvariantCulture)",
			"bool" => $"bool.Parse({variableName})",
			"decimal" => $"decimal.Parse({variableName}, CultureInfo.InvariantCulture)",
			"DateTime" => $"DateTime.Parse({variableName}, CultureInfo.InvariantCulture)",
			"Guid" => $"Guid.Parse({variableName})",
			"TimeSpan" => $"TimeSpan.Parse({variableName}, CultureInfo.InvariantCulture)",
			"DateTimeOffset" => $"DateTimeOffset.Parse({variableName}, CultureInfo.InvariantCulture)",
			_ => variableName,
		};
	}

	private static string GetSimpleTypeName(ITypeSymbol type)
	{
		return type.SpecialType switch
		{
			SpecialType.System_String => "string",
			SpecialType.System_Int32 => "int",
			SpecialType.System_Int64 => "long",
			SpecialType.System_Single => "float",
			SpecialType.System_Double => "double",
			SpecialType.System_Boolean => "bool",
			SpecialType.System_Decimal => "decimal",
			SpecialType.System_DateTime => "DateTime",
			_ => type.ToDisplayString() switch
			{
				"System.Guid" => "Guid",
				"System.TimeSpan" => "TimeSpan",
				"System.DateTimeOffset" => "DateTimeOffset",
				var other => other
			}
		};
	}

	private static string GetToStringExpression(string expression, ValueInfo value)
	{
		if (value.IsCollection)
		{
			string elementToString = value.CollectionElementTypeName switch
			{
				"string" => "e",
				"bool" => "e.ToString()",
				"DateTime" or "TimeSpan" or "DateTimeOffset" => "e.ToString(CultureInfo.InvariantCulture)",
				"int" or "long" or "float" or "double" or "decimal" => "e.ToString(CultureInfo.InvariantCulture)",
				"Guid" => "e.ToString()",
				_ => "e?.ToString() ?? string.Empty"
			};
			return $"string.Join(\",\", {expression}.Select(e => {elementToString}))";
		}

		return value.IsEnum && value.EnumFullName is not null
			? value.IsFlagsEnum
				? $"string.Join(\" \", Enum.GetValues(typeof({value.EnumFullName})).Cast<{value.EnumFullName}>().Where(flag => flag != 0 && {expression}.HasFlag(flag)).Select(flag => flag.ToString()))"
				: $"{expression}.ToString()"
			: value.TypeName switch
			{
				"string" => expression,
				"bool" => $"{expression}.ToString()",
				"DateTime" or "DateTimeOffset" => $"{expression}.ToString(CultureInfo.InvariantCulture)",
				"TimeSpan" => $"{expression}.ToString(\"c\", CultureInfo.InvariantCulture)",
				"Guid" => $"{expression}.ToString()",
				"int" or "long" or "float" or "double" or "decimal" =>
					$"{expression}.ToString(CultureInfo.InvariantCulture)",
				_ => $"{expression}?.ToString() ?? string.Empty",
			};
	}

	private static string GetStringComparison(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return "OrdinalIgnoreCase";

		foreach (AttributeData attr in classSymbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() != GeneratorAttributeName)
				continue;

			if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int comparisonValue)
			{
				return comparisonValue switch
				{
					0 => "CurrentCulture",
					1 => "CurrentCultureIgnoreCase",
					2 => "InvariantCulture",
					3 => "InvariantCultureIgnoreCase",
					4 => "Ordinal",
					5 => "OrdinalIgnoreCase",
					_ => "OrdinalIgnoreCase"
				};
			}
		}

		return "OrdinalIgnoreCase";
	}

	private static string GetSectionDelimiter(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return ".";

		foreach (AttributeData attr in classSymbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() != GeneratorAttributeName)
				continue;

			if (attr.ConstructorArguments.Length > 1 && attr.ConstructorArguments[1].Value is string delimiterValue)
				return delimiterValue;
		}

		return ".";
	}

	private static bool GetSerializeComments(ClassDeclarationSyntax classDeclaration)
	{
		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != AttributeShortName && name != AttributeFullName)
					continue;

				if (attribute.ArgumentList is null)
					continue;

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					if (argument.NameEquals?.Name.Identifier.Text == "SerializeComments")
					{
						string expressionText = argument.Expression.ToString();
						if (expressionText == "true")
							return true;
					}
				}
			}
		}

		return false;
	}

	private static string? GetXmlSummaryComment(ISymbol symbol)
	{
		foreach (SyntaxReference syntaxRef in symbol.DeclaringSyntaxReferences)
		{
			SyntaxNode node = syntaxRef.GetSyntax();

			if (!node.HasLeadingTrivia)
				continue;

			foreach (SyntaxTrivia trivia in node.GetLeadingTrivia())
			{
				if (trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia))
				{
					SyntaxNode? structure = trivia.GetStructure();
					if (structure is null)
						continue;

					foreach (SyntaxNode child in structure.ChildNodes())
					{
						if (child is not XmlElementSyntax xmlElement)
							continue;

						if (xmlElement.StartTag.Name.ToString() != "summary")
							continue;

						string content = xmlElement.Content.ToString();
						string[] lines = content.Split(LineBreakSeparators, StringSplitOptions.RemoveEmptyEntries);

						List<string> cleanLines = [];
						foreach (string line in lines)
						{
							string trimmed = line.Trim().TrimStart('/').Trim();
							if (trimmed.Length > 0)
								cleanLines.Add(trimmed);
						}

						if (cleanLines.Count > 0)
							return string.Join(" ", cleanLines);
					}
				}
			}
		}

		return null;
	}

	private static string BuildNullCheck(string propertyPath)
	{
		string[] segments = propertyPath.Split('.');
		if (segments.Length <= 2)
			return $"{propertyPath} != null";

		List<string> checks = [];
		for (int i = 1; i < segments.Length; i++)
		{
			checks.Add($"{string.Join(".", segments, 0, i + 1)} != null");
		}

		return string.Join(" && ", checks);
	}

	private sealed record SectionInfo(
		string PropertyName,
		string PropertyPath,
		string SectionName,
		string TypeName,
		bool NeedsInitialization,
		List<ValueInfo> Values,
		string? Comment = null
	);

	private sealed record ValueInfo(
		string PropertyName,
		string KeyName,
		string TypeName,
		bool IsEnum = false,
		bool IsFlagsEnum = false,
		string? EnumFullName = null,
		string? Comment = null,
		bool IsCollection = false,
		string? CollectionElementTypeName = null,
		bool IsArray = false
	);
}
