// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating notification properties for classes marked
/// with the <see cref="GenerateNotificationsAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NotificationsGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(NotificationsGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateNotificationsAttribute).FullName;
	private const string AttributeFullName = nameof(GenerateNotificationsAttribute);
	private static readonly string AttributeShortName = GeneratorHelpers.StripAttributeSuffix(AttributeFullName);

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		(bool generatePropertyChanged, bool generatePropertyChanging, bool generateHasChanged) = GetAttributeOptions(ctx.ClassDeclaration);

		if (!generatePropertyChanged && !generatePropertyChanging)
			return;

		List<FieldDeclarationSyntax> members = [.. ctx.ClassDeclaration.Members
			.OfType<FieldDeclarationSyntax>()
			.Where(field => field is not null)];

		bool isSealed = ctx.ClassDeclaration.Modifiers.Any(SyntaxKind.SealedKeyword);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		AppendUsings(sb);
		sb.AppendLine($"namespace {ctx.NamespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in ctx.OuterClasses)
		{
			string ind = new(' ', baseIndent * 2);
			sb.AppendLine($"{ind}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{ind}{{");
			baseIndent++;
		}

		AppendClassStart(sb, ctx.ClassName, ctx.Accessibility, generatePropertyChanged, generatePropertyChanging, generateHasChanged, baseIndent);
		AppendProperties(sb, members, generatePropertyChanged, generatePropertyChanging, generateHasChanged, baseIndent + 1);
		AppendRaiseMethods(sb, generatePropertyChanged, generatePropertyChanging, isSealed, baseIndent + 1);

		string classIndent = new(' ', baseIndent * 2);
		sb.AppendLine($"{classIndent}}}");

		for (int i = ctx.OuterClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string ind = new(' ', baseIndent * 2);
			sb.AppendLine($"{ind}}}");
		}

		sb.AppendLine("}");

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.g.cs"
			: $"{ctx.ClassName}.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static (bool propertyChanged, bool propertyChanging, bool hasChanged) GetAttributeOptions(ClassDeclarationSyntax classDeclaration)
	{
		bool propertyChanged = true;
		bool propertyChanging = true;
		bool hasChanged = false;

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != AttributeShortName && name != AttributeFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return (propertyChanged, propertyChanging, hasChanged);

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string? paramName = argument.NameColon?.Name.Identifier.Text;
					string argText = argument.Expression.ToString();

					if (!bool.TryParse(argText, out bool value))
						continue;

					switch (paramName)
					{
						case "propertyChanged":
							propertyChanged = value;
							break;
						case "propertyChanging":
							propertyChanging = value;
							break;
						case "hasChanged":
							hasChanged = value;
							break;
						default:
							// Positional: first=propertyChanged, second=propertyChanging, third=hasChanged
							int index = attribute.ArgumentList.Arguments.IndexOf(argument);
							if (index == 0)
								propertyChanged = value;
							else if (index == 1)
								propertyChanging = value;
							else if (index == 2)
								hasChanged = value;
							break;
					}
				}

				return (propertyChanged, propertyChanging, hasChanged);
			}
		}

		return (propertyChanged, propertyChanging, hasChanged);
	}

	private static void AppendClassStart(StringBuilder sb, string className, string accessibility, bool propertyChanged, bool propertyChanging, bool hasChanged, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string innerIndent = new(' ', (indentLevel + 1) * 2);
		string bodyIndent = new(' ', (indentLevel + 2) * 2);
		string deepIndent = new(' ', (indentLevel + 3) * 2);
		string deeperIndent = new(' ', (indentLevel + 4) * 2);

		List<string> interfaces = [];

		if (propertyChanged)
			interfaces.Add("INotifyPropertyChanged");
		if (propertyChanging)
			interfaces.Add("INotifyPropertyChanging");

		string baseList = interfaces.Count > 0 ? $" : {string.Join(", ", interfaces)}" : string.Empty;

		sb.AppendLine($"{indent}{accessibility} partial class {className}{baseList}");
		sb.AppendLine($"{indent}{{");

		if (propertyChanged)
		{
			sb.AppendLine($"{innerIndent}/// <inheritdoc/>");
			sb.AppendLine($"{innerIndent}public event PropertyChangedEventHandler? PropertyChanged;");
			sb.AppendLine();
		}

		if (propertyChanging)
		{
			sb.AppendLine($"{innerIndent}/// <inheritdoc/>");
			sb.AppendLine($"{innerIndent}public event PropertyChangingEventHandler? PropertyChanging;");
			sb.AppendLine();
		}

		if (hasChanged)
		{
			sb.AppendLine($"{innerIndent}private bool _hasChanged;");
			sb.AppendLine();
			sb.AppendLine($"{innerIndent}/// <summary>");
			sb.AppendLine($"{innerIndent}/// Gets or sets a value indicating whether the object has been changed.");
			sb.AppendLine($"{innerIndent}/// </summary>");
			sb.AppendLine($"{innerIndent}public bool HasChanged");
			sb.AppendLine($"{innerIndent}{{");
			sb.AppendLine($"{bodyIndent}get => _hasChanged;");
			sb.AppendLine($"{bodyIndent}set");
			sb.AppendLine($"{bodyIndent}{{");
			sb.AppendLine($"{deepIndent}if (_hasChanged != value)");
			sb.AppendLine($"{deepIndent}{{");
			if (propertyChanging)
				sb.AppendLine($"{deeperIndent}RaisePropertyChanging(nameof(HasChanged));");
			sb.AppendLine($"{deeperIndent}_hasChanged = value;");
			if (propertyChanged)
				sb.AppendLine($"{deeperIndent}RaisePropertyChanged(nameof(HasChanged));");
			sb.AppendLine($"{deepIndent}}}");
			sb.AppendLine($"{bodyIndent}}}");
			sb.AppendLine($"{innerIndent}}}");
			sb.AppendLine();
		}
	}

	private static void AppendProperties(StringBuilder sb, List<FieldDeclarationSyntax> members, bool propertyChanged, bool propertyChanging, bool hasChanged, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);
		string deepIndent = new(' ', (indentLevel + 2) * 2);
		string deeperIndent = new(' ', (indentLevel + 3) * 2);

		sb.AppendLine(string.Join(Environment.NewLine, members.SelectMany(member =>
				member.Declaration.Variables.Select(variable =>
				{
					string fieldName = variable.Identifier.Text;
					string fieldType = $"{member.Declaration.Type}";
					string propertyName = FieldNameToPropertyName(fieldName);

					StringBuilder propertySb = new();
					propertySb.AppendLine($"{indent}public {fieldType} {propertyName}");
					propertySb.AppendLine($"{indent}{{");
					propertySb.AppendLine($"{bodyIndent}get => {fieldName};");
					propertySb.AppendLine($"{bodyIndent}set");
					propertySb.AppendLine($"{bodyIndent}{{");
					propertySb.AppendLine($"{deepIndent}if ({fieldName} != value)");
					propertySb.AppendLine($"{deepIndent}{{");
					if (propertyChanging)
						propertySb.AppendLine($"{deeperIndent}RaisePropertyChanging(nameof({propertyName}));");
					propertySb.AppendLine($"{deeperIndent}{fieldName} = value;");
					if (propertyChanged)
						propertySb.AppendLine($"{deeperIndent}RaisePropertyChanged(nameof({propertyName}));");
					if (hasChanged)
						propertySb.AppendLine($"{deeperIndent}HasChanged = true;");
					propertySb.AppendLine($"{deepIndent}}}");
					propertySb.AppendLine($"{bodyIndent}}}");
					propertySb.Append($"{indent}}}");

					return propertySb.ToString();
				}))));
	}

	private static void AppendRaiseMethods(StringBuilder sb, bool propertyChanged, bool propertyChanging, bool isSealed, int indentLevel)
	{
		string indent = new(' ', indentLevel * 2);
		string bodyIndent = new(' ', (indentLevel + 1) * 2);

		string methodModifier = isSealed ? "private" : "protected virtual";

		if (propertyChanging)
		{
			sb.AppendLine();
			sb.AppendLine($"{indent}/// <summary>");
			sb.AppendLine($"{indent}/// Raises the <see cref=\"PropertyChanging\"/> event to notify subscribers that a property");
			sb.AppendLine($"{indent}/// is about to change.");
			sb.AppendLine($"{indent}/// </summary>");
			sb.AppendLine($"{indent}/// <param name=\"propertyName\">The name of the property that is changing.</param>");
			sb.AppendLine($"{indent}{methodModifier} void RaisePropertyChanging(string propertyName)");
			sb.AppendLine($"{bodyIndent}=> PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propertyName));");
		}

		if (propertyChanged)
		{
			sb.AppendLine();
			sb.AppendLine($"{indent}/// <summary>");
			sb.AppendLine($"{indent}/// Raises the <see cref=\"PropertyChanged\"/> event to notify subscribers that a property");
			sb.AppendLine($"{indent}/// has changed.");
			sb.AppendLine($"{indent}/// </summary>");
			sb.AppendLine($"{indent}/// <param name=\"propertyName\">The name of the property that has changed.</param>");
			sb.AppendLine($"{indent}{methodModifier} void RaisePropertyChanged(string propertyName)");
			sb.AppendLine($"{bodyIndent}=> PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
		}
	}

	private static void AppendUsings(StringBuilder sb)
	{
		sb.AppendLine("using System;");
		sb.AppendLine("using System.ComponentModel;");
		sb.AppendLine();
	}

	/// <summary>
	/// Converts a field name to a property name by removing any leading underscores
	/// and capitalizing the first letter.
	/// </summary>
	/// <param name="fieldName">The field name to convert.</param>
	/// <returns>The converted property name.</returns>
	private static string FieldNameToPropertyName(string fieldName)
	{
		if (fieldName.StartsWith("_", StringComparison.OrdinalIgnoreCase))
			fieldName = fieldName[1..];
		return $"{char.ToUpperInvariant(fieldName[0])}{fieldName[1..]}";
	}
}
