// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating notification properties for classes marked
/// with the <see cref="GenerateNotificationsAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NotificationsGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorAttributeName = typeof(GenerateNotificationsAttribute).FullName;
	private const string AttributeFullName = nameof(GenerateNotificationsAttribute);
	private static readonly string AttributeShortName = GeneratorHelpers.StripAttributeSuffix(AttributeFullName);

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		(bool generatePropertyChanged, bool generatePropertyChanging, bool generateHasChanged) = GetAttributeOptions(ctx.ClassDeclaration);

		if (!generatePropertyChanged && !generatePropertyChanging)
			return;

		List<FieldDeclarationSyntax> members = [.. ctx.ClassDeclaration.Members
			.OfType<FieldDeclarationSyntax>()
			.Where(field => field is not null)
			.Where(field => !HasAttribute(field, nameof(ExcludeFromNotificationAttribute)))];

		bool isSealed = ctx.ClassDeclaration.Modifiers.Any(SyntaxKind.SealedKeyword);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.NotificationsGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendUsing(NamespaceNames.SystemComponentModel);
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendClassStart(sb, ctx.ClassName, ctx.Accessibility, generatePropertyChanged, generatePropertyChanging, generateHasChanged);
		AppendProperties(sb, members, generatePropertyChanged, generatePropertyChanging, generateHasChanged);
		AppendRaiseMethods(sb, generatePropertyChanged, generatePropertyChanging, isSealed);

		sb.CloseClass();
		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.g.cs"
			: $"{ctx.ClassName}.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static (bool propertyChanged, bool propertyChanging, bool hasChanged) GetAttributeOptions(ClassDeclarationSyntax classDeclaration)
	{
		bool propertyChanged = true;
		bool propertyChanging = true;
		bool hasChanged = false;

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != AttributeShortName && name != AttributeFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return (propertyChanged, propertyChanging, hasChanged);

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string? paramName = argument.NameColon?.Name.Identifier.Text;
					string argText = argument.Expression.ToString();

					if (!bool.TryParse(argText, out bool value))
						continue;

					switch (paramName)
					{
						case "propertyChanged":
							propertyChanged = value;
							break;
						case "propertyChanging":
							propertyChanging = value;
							break;
						case "hasChanged":
							hasChanged = value;
							break;
						default:
							// Positional: first=propertyChanged, second=propertyChanging, third=hasChanged
							int index = attribute.ArgumentList.Arguments.IndexOf(argument);
							if (index == 0)
								propertyChanged = value;
							else if (index == 1)
								propertyChanging = value;
							else if (index == 2)
								hasChanged = value;
							break;
					}
				}

				return (propertyChanged, propertyChanging, hasChanged);
			}
		}

		return (propertyChanged, propertyChanging, hasChanged);
	}

	private static void AppendClassStart(SourceBuilder sb, string className, string accessibility, bool propertyChanged, bool propertyChanging, bool hasChanged)
	{
		List<string> interfaces = [];

		if (propertyChanged)
			interfaces.Add("INotifyPropertyChanged");
		if (propertyChanging)
			interfaces.Add("INotifyPropertyChanging");

		string? baseTypes = interfaces.Count > 0 ? string.Join(", ", interfaces) : null;

		sb.OpenClass(accessibility, className, baseTypes);

		if (propertyChanged)
		{
			sb.AppendLine("/// <inheritdoc/>");
			sb.AppendLine("public event PropertyChangedEventHandler? PropertyChanged;");
			sb.AppendLine();
		}

		if (propertyChanging)
		{
			sb.AppendLine("/// <inheritdoc/>");
			sb.AppendLine("public event PropertyChangingEventHandler? PropertyChanging;");
			sb.AppendLine();
		}

		if (hasChanged)
		{
			sb.AppendLine("private bool _hasChanged;");
			sb.AppendLine();
			sb.AppendLine("/// <summary>");
			sb.AppendLine("/// Gets or sets a value indicating whether the object has been changed.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine("public bool HasChanged");
			sb.OpenBrace();
			sb.AppendLine("get => _hasChanged;");
			sb.AppendLine("set");
			sb.OpenBrace();
			sb.AppendLine("if (_hasChanged != value)");
			sb.OpenBrace();
			if (propertyChanging)
				sb.AppendLine("RaisePropertyChanging(nameof(HasChanged));");
			sb.AppendLine("_hasChanged = value;");
			if (propertyChanged)
				sb.AppendLine("RaisePropertyChanged(nameof(HasChanged));");
			sb.CloseBrace();
			sb.CloseBrace();
			sb.CloseBrace();
			sb.AppendLine();
		}
	}

	private static void AppendProperties(SourceBuilder sb, List<FieldDeclarationSyntax> members, bool propertyChanged, bool propertyChanging, bool hasChanged)
	{
		bool first = true;
		foreach (FieldDeclarationSyntax member in members)
		{
			List<string> alsoNotifyFor = GetAlsoNotifyForProperties(member);

			foreach (VariableDeclaratorSyntax variable in member.Declaration.Variables)
			{
				if (!first)
					sb.AppendLine();
				first = false;

				string fieldName = variable.Identifier.Text;
				string fieldType = $"{member.Declaration.Type}";
				string propertyName = FieldNameToPropertyName(fieldName);

				sb.AppendLine($"public {fieldType} {propertyName}");
				sb.OpenBrace();
				sb.AppendLine($"get => {fieldName};");
				sb.AppendLine("set");
				sb.OpenBrace();
				sb.AppendLine($"if ({fieldName} != value)");
				sb.OpenBrace();
				if (propertyChanging)
				{
					if (alsoNotifyFor.Count == 0)
						sb.AppendLine($"RaisePropertyChanging(nameof({propertyName}));");
					else
						sb.AppendLine($"RaisePropertyChanging(nameof({propertyName}), {string.Join(", ", alsoNotifyFor.Select(p => $"nameof({p})"))});");
				}
				sb.AppendLine($"{fieldName} = value;");
				if (propertyChanged)
				{
					if (alsoNotifyFor.Count == 0)
						sb.AppendLine($"RaisePropertyChanged(nameof({propertyName}));");
					else
						sb.AppendLine($"RaisePropertyChanged(nameof({propertyName}), {string.Join(", ", alsoNotifyFor.Select(p => $"nameof({p})"))});");
				}
				if (hasChanged)
					sb.AppendLine("HasChanged = true;");
				sb.CloseBrace();
				sb.CloseBrace();
				sb.CloseBrace();
			}
		}
	}

	private static void AppendRaiseMethods(SourceBuilder sb, bool propertyChanged, bool propertyChanging, bool isSealed)
	{
		string methodModifier = isSealed ? "private" : "protected virtual";

		if (propertyChanging)
		{
			sb.AppendLine();
			sb.AppendLine("/// <summary>");
			sb.AppendLine("/// Raises the <see cref=\"PropertyChanging\"/> event to notify subscribers that a property");
			sb.AppendLine("/// is about to change.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine("/// <param name=\"propertyName\">The name of the property that is changing.</param>");
			sb.AppendLine($"{methodModifier} void RaisePropertyChanging(string propertyName)");
			sb.Indent();
			sb.AppendLine("=> PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propertyName));");
			sb.Outdent();
			sb.AppendLine();
			sb.AppendLine("/// <summary>");
			sb.AppendLine("/// Raises the <see cref=\"PropertyChanging\"/> event to notify subscribers that a property");
			sb.AppendLine("/// is about to change.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine("/// <param name=\"propertyNames\">The names of the properties that are changing.</param>");
			sb.AppendLine($"{methodModifier} void RaisePropertyChanging(params string[] propertyNames)");
			sb.AppendLine("{");
			sb.Indent();
			sb.AppendLine("foreach(string propertyName in propertyNames)");
			sb.Indent();
			sb.AppendLine("RaisePropertyChanging(propertyName);");
			sb.Outdent();
			sb.Outdent();
			sb.AppendLine("}");
		}

		if (propertyChanged)
		{
			sb.AppendLine();
			sb.AppendLine("/// <summary>");
			sb.AppendLine("/// Raises the <see cref=\"PropertyChanged\"/> event to notify subscribers that a property");
			sb.AppendLine("/// has changed.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine("/// <param name=\"propertyName\">The name of the property that has changed.</param>");
			sb.AppendLine($"{methodModifier} void RaisePropertyChanged(string propertyName)");
			sb.Indent();
			sb.AppendLine("=> PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
			sb.Outdent();
			sb.AppendLine();
			sb.AppendLine("/// <summary>");
			sb.AppendLine("/// Raises the <see cref=\"PropertyChanged\"/> event to notify subscribers that a property");
			sb.AppendLine("/// has changed.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine("/// <param name=\"propertyNames\">The names of the properties that have changed.</param>");
			sb.AppendLine($"{methodModifier} void RaisePropertyChanged(params string[] propertyNames)");
			sb.AppendLine("{");
			sb.Indent();
			sb.AppendLine("foreach(string propertyName in propertyNames)");
			sb.Indent();
			sb.AppendLine("RaisePropertyChanged(propertyName);");
			sb.Outdent();
			sb.Outdent();
			sb.AppendLine("}");
		}
	}

	/// <summary>
	/// Converts a field name to a property name by removing any leading underscores
	/// and capitalizing the first letter.
	/// </summary>
	/// <param name="fieldName">The field name to convert.</param>
	/// <returns>The converted property name.</returns>
	private static string FieldNameToPropertyName(string fieldName)
	{
		if (fieldName.StartsWith("_", StringComparison.OrdinalIgnoreCase))
			fieldName = fieldName[1..];
		return $"{char.ToUpperInvariant(fieldName[0])}{fieldName[1..]}";
	}

	private static bool HasAttribute(FieldDeclarationSyntax field, string attributeName)
	{
		string shortName = GeneratorHelpers.StripAttributeSuffix(attributeName);

		foreach (AttributeListSyntax attributeList in field.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();
				if (name == attributeName || name == shortName)
					return true;
			}
		}

		return false;
	}

	private static List<string> GetAlsoNotifyForProperties(FieldDeclarationSyntax field)
	{
		List<string> properties = [];
		string fullName = nameof(AlsoNotifyAttribute);
		string shortName = GeneratorHelpers.StripAttributeSuffix(fullName);

		foreach (AttributeListSyntax attributeList in field.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();
				if (name != fullName && name != shortName)
					continue;

				if (attribute.ArgumentList is null)
					continue;

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string argText = argument.Expression.ToString();

					if (argText.StartsWith("nameof(", StringComparison.Ordinal))
						argText = argText[7..^1];
					else if (argText.StartsWith("\"", StringComparison.Ordinal))
						argText = argText.Trim('"');

					if (!string.IsNullOrWhiteSpace(argText))
						properties.Add(argText);
				}
			}
		}

		return properties;
	}
}
