// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating the singleton pattern for classes marked
/// with the <see cref="GenerateSingletonAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SingletonGenerator : IIncrementalGenerator
{
	private const string AttributeShortName = "GenerateSingleton";
	private const string AttributeFullName = "GenerateSingletonAttribute";
	private static readonly string GeneratorName = typeof(SingletonGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateSingletonAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		// Check for required members that prevent parameterless initialization
		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is IPropertySymbol propertySymbol && propertySymbol.IsRequired)
			{
				Diagnostic diagnostic = Diagnostic.Create(
					DiagnosticDescriptors.SingletonRequiresParameterlessInitializationDiagnostic,
					classDeclaration.Identifier.GetLocation(),
					classSymbol.Name,
					propertySymbol.Name);
				context.ReportDiagnostic(diagnostic);
				return;
			}

			if (member is IFieldSymbol fieldSymbol && fieldSymbol.IsRequired)
			{
				Diagnostic diagnostic = Diagnostic.Create(
					DiagnosticDescriptors.SingletonRequiresParameterlessInitializationDiagnostic,
					classDeclaration.Identifier.GetLocation(),
					classSymbol.Name,
					fieldSymbol.Name);
				context.ReportDiagnostic(diagnostic);
				return;
			}
		}

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GeneratorHelpers.GetAccessibility(classDeclaration);
		bool useLazy = GetUseLazy(classDeclaration);
		string instanceTypeName = GetFirstInterfaceName(classSymbol) ?? className;

		List<(string Accessibility, string Name)> outerClasses = GeneratorHelpers.GetOuterClasses(classDeclaration);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in outerClasses)
		{
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{indent}{{");
			baseIndent++;
		}

		AppendPartialClass(sb, className, accessibility, useLazy, instanceTypeName, baseIndent);

		for (int i = outerClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}}}");
		}

		sb.AppendLine("}");

		string hintName = outerClasses.Count > 0
			? $"{string.Join(".", outerClasses.Select(o => o.Name))}.{className}.Singleton.g.cs"
			: $"{className}.Singleton.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, bool useLazy, string instanceTypeName, int indentLevel = 1)
	{
		string indent = new(' ', indentLevel * 2);
		string innerIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}{accessibility} partial class {className}");
		sb.AppendLine($"{indent}{{");

		if (useLazy)
		{
			sb.AppendLine($"{innerIndent}private static readonly Lazy<{className}> _lazyInstance = new Lazy<{className}>(() => new {className}());");
			sb.AppendLine();
			sb.AppendLine($"{innerIndent}/// <summary>");
			if (instanceTypeName != className)
				sb.AppendLine($"{innerIndent}/// Gets the singleton instance of <see cref=\"{className}\"/> as <see cref=\"{instanceTypeName}\"/>.");
			else
				sb.AppendLine($"{innerIndent}/// Gets the singleton instance of <see cref=\"{className}\"/>.");
			sb.AppendLine($"{innerIndent}/// </summary>");
			sb.AppendLine($"{innerIndent}public static {instanceTypeName} Instance => _lazyInstance.Value;");
		}
		else
		{
			sb.AppendLine($"{innerIndent}/// <summary>");
			if (instanceTypeName != className)
				sb.AppendLine($"{innerIndent}/// Gets the singleton instance of <see cref=\"{className}\"/> as <see cref=\"{instanceTypeName}\"/>.");
			else
				sb.AppendLine($"{innerIndent}/// Gets the singleton instance of <see cref=\"{className}\"/>.");
			sb.AppendLine($"{innerIndent}/// </summary>");
			sb.AppendLine($"{innerIndent}public static {instanceTypeName} Instance {{ get; }} = new {className}();");
		}

		sb.AppendLine();
		sb.AppendLine($"{innerIndent}private {className}() {{ }}");
		sb.AppendLine($"{indent}}}");
	}

	private static bool GetUseLazy(ClassDeclarationSyntax classDeclaration)
	{
		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not AttributeShortName and not AttributeFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return true;

				AttributeArgumentSyntax firstArg = attribute.ArgumentList.Arguments[0];
				string argText = firstArg.Expression.ToString();

				if (bool.TryParse(argText, out bool result))
					return result;
			}
		}

		return true;
	}

	private static string? GetFirstInterfaceName(INamedTypeSymbol classSymbol)
		=> classSymbol.Interfaces.FirstOrDefault()?.Name;
}
