// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating the singleton pattern for classes marked
/// with the <see cref="GenerateSingletonAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SingletonGenerator : IIncrementalGenerator
{
	private const string AttributeFullName = nameof(GenerateSingletonAttribute);
	private static readonly string AttributeShortName = GeneratorHelpers.StripAttributeSuffix(AttributeFullName);
	private static readonly string GeneratorAttributeName = typeof(GenerateSingletonAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		// Check for required members that prevent parameterless initialization
		foreach (ISymbol member in ctx.ClassSymbol.GetMembers())
		{
			if (member is IPropertySymbol propertySymbol && propertySymbol.IsRequired)
			{
				Diagnostic diagnostic = Diagnostic.Create(
					DiagnosticDescriptors.SingletonRequiresParameterlessInitializationDiagnostic,
					ctx.ClassDeclaration.Identifier.GetLocation(),
					ctx.ClassName,
					propertySymbol.Name);
				context.ReportDiagnostic(diagnostic);
				return;
			}

			if (member is IFieldSymbol fieldSymbol && fieldSymbol.IsRequired)
			{
				Diagnostic diagnostic = Diagnostic.Create(
					DiagnosticDescriptors.SingletonRequiresParameterlessInitializationDiagnostic,
					ctx.ClassDeclaration.Identifier.GetLocation(),
					ctx.ClassName,
					fieldSymbol.Name);
				context.ReportDiagnostic(diagnostic);
				return;
			}
		}

		bool useLazy = GetUseLazy(ctx.ClassDeclaration);
		string instanceTypeName = GetFirstInterfaceName(ctx.ClassSymbol) ?? ctx.ClassName;

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.SingletonGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, useLazy, instanceTypeName);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.Singleton.g.cs"
			: $"{ctx.ClassName}.Singleton.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, bool useLazy, string instanceTypeName)
	{
		sb.OpenClass(accessibility, className);

		if (useLazy)
		{
			sb.AppendLine($"private static readonly Lazy<{className}> _lazyInstance = new Lazy<{className}>(() => new {className}());");
			sb.AppendLine();
			sb.AppendLine("/// <summary>");
			if (instanceTypeName != className)
				sb.AppendLine($"/// Gets the singleton instance of <see cref=\"{className}\"/> as <see cref=\"{instanceTypeName}\"/>.");
			else
				sb.AppendLine($"/// Gets the singleton instance of <see cref=\"{className}\"/>.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine($"public static {instanceTypeName} Instance => _lazyInstance.Value;");
		}
		else
		{
			sb.AppendLine("/// <summary>");
			if (instanceTypeName != className)
				sb.AppendLine($"/// Gets the singleton instance of <see cref=\"{className}\"/> as <see cref=\"{instanceTypeName}\"/>.");
			else
				sb.AppendLine($"/// Gets the singleton instance of <see cref=\"{className}\"/>.");
			sb.AppendLine("/// </summary>");
			sb.AppendLine($"public static {instanceTypeName} Instance {{ get; }} = new {className}();");
		}

		sb.AppendLine();
		sb.AppendLine($"private {className}() {{ }}");
		sb.CloseClass();
	}

	private static bool GetUseLazy(ClassDeclarationSyntax classDeclaration)
	{
		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != AttributeShortName && name != AttributeFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return true;

				AttributeArgumentSyntax firstArg = attribute.ArgumentList.Arguments[0];
				string argText = firstArg.Expression.ToString();

				if (bool.TryParse(argText, out bool result))
					return result;
			}
		}

		return true;
	}

	private static string? GetFirstInterfaceName(INamedTypeSymbol classSymbol)
		=> classSymbol.Interfaces.FirstOrDefault()?.Name;
}
