// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a <c>ToString()</c> override for classes marked
/// with the <see cref="GenerateToStringAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ToStringGenerator : IIncrementalGenerator
{
	private static readonly (string MetadataName, string FullName, string ShortName) AttributeNames =
		GeneratorHelpers.GetAttributeNames<GenerateToStringAttribute>();

	private static readonly string ToStringFormatAttributeName = typeof(ToStringFormatAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, AttributeNames.MetadataName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		CollectionFormat collectionFormat = GetCollectionFormat(ctx.ClassDeclaration, ctx.SemanticModel);
		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(ctx.ClassDeclaration, ctx.SemanticModel, nameof(GenerateToStringAttribute));
		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, excludedProperties, detectCollections: true, toStringFormatAttributeName: ToStringFormatAttributeName);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.ToStringGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendUsing(NamespaceNames.SystemCollectionsGeneric);
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, properties, collectionFormat);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.ToString.g.cs"
			: $"{ctx.ClassName}.ToString.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, ImmutableArray<PropertyDescriptor> properties, CollectionFormat collectionFormat)
	{
		bool hasDictionary = collectionFormat == CollectionFormat.Elements
			&& properties.Any(static p => p.CollectionKind == CollectionKind.Dictionary);

		sb.OpenClass(accessibility, className);
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public override string ToString()");
		sb.OpenBrace();

		if (properties.Length == 0)
		{
			sb.AppendLine($"return \"{className} {{ }}\";");
		}
		else
		{
			foreach (PropertyDescriptor prop in properties)
			{
				if (prop.CollectionKind == CollectionKind.None)
					continue;

				sb.AppendLine($"string {prop.Name.ToLowerInvariant()} = {BuildCollectionFormatExpression(prop, collectionFormat)};");
			}

			sb.AppendLine($"return $\"{className} {{{{ {BuildFormatString(properties)} }}}}\";");
		}

		sb.CloseBrace();

		if (hasDictionary)
		{
			sb.AppendLine();
			AppendDictionaryFormatHelper(sb);
		}

		sb.CloseClass();
	}

	private static string BuildFormatString(ImmutableArray<PropertyDescriptor> properties)
	{
		StringBuilder format = new();

		for (int i = 0; i < properties.Length; i++)
		{
			if (i > 0)
				format.Append(", ");

			string token = properties[i].CollectionKind != CollectionKind.None
				? $"{properties[i].Name.ToLowerInvariant()}"
				: properties[i].FormatString is not null
					? $"{properties[i].Name}:{properties[i].FormatString}"
					: properties[i].Name;

			format.Append($"{{nameof({properties[i].Name})}} = {{{token}}}");
		}

		return format.ToString();
	}

	private static string BuildCollectionFormatExpression(PropertyDescriptor prop, CollectionFormat format)
	{
		bool isImmutableArray = prop.CollectionKind == CollectionKind.ImmutableArray;
		bool isArray = prop.CollectionKind == CollectionKind.Array;
		bool isDictionary = prop.CollectionKind == CollectionKind.Dictionary;

		// ImmutableArray<T> (non-nullable struct): IsValueType = true
		// ImmutableArray<T>? (Nullable<ImmutableArray<T>>): IsValueType = false
		bool isNullableImmutableArray = isImmutableArray && !prop.IsValueType;
		bool isNonNullableImmutableArray = isImmutableArray && prop.IsValueType;

		// Arrays and ImmutableArrays use .Length; all other collection types use .Count
		bool usesLength = isArray || isImmutableArray;

		// Expression for the non-null collection value
		string directAccess = isNullableImmutableArray ? $"{prop.Name}.Value" : prop.Name;
		string countAccess = usesLength ? $"{directAccess}.Length" : $"{directAccess}.Count";

		// Null guard (null means no null check required for non-nullable value types)
		string? nullGuard = isNonNullableImmutableArray
			? null
			: isNullableImmutableArray
				? $"!{prop.Name}.HasValue"
				: $"{prop.Name} == null";

		string WrapGuard(string valueExpr)
			=> nullGuard is not null ? $"{nullGuard} ? \"null\" : {valueExpr}" : valueExpr;

		return format switch
		{
			CollectionFormat.Elements when isDictionary => $"DictionaryToString({prop.Name})",// The DictionaryToString helper handles null internally
			CollectionFormat.Elements => WrapGuard($"\"[\" + string.Join(\", \", {directAccess}) + \"]\""),
			CollectionFormat.Count => WrapGuard($"\"Count = \" + {countAccess}"),
			CollectionFormat.TypeAndCount => WrapGuard($"{directAccess}.GetType().Name + \" (Count = \" + {countAccess} + \")\""),
			_ => prop.Name,
		};
	}

	private static void AppendDictionaryFormatHelper(SourceBuilder sb)
	{
		sb.AppendLine("private static string DictionaryToString<TKey, TValue>(IDictionary<TKey, TValue>? dictionary)");
		sb.OpenBrace();
		sb.AppendLine("if (dictionary == null)");
		sb.Indent();
		sb.AppendLine("return \"null\";");
		sb.Outdent();
		sb.AppendLine("List<string> parts = new List<string>(dictionary.Count);");
		sb.AppendLine("foreach (KeyValuePair<TKey, TValue> kvp in dictionary)");
		sb.Indent();
		sb.AppendLine("parts.Add(kvp.Key + \": \" + kvp.Value);");
		sb.Outdent();
		sb.AppendLine("return \"{\" + string.Join(\", \", parts) + \"}\";");
		sb.CloseBrace();
	}

	private static CollectionFormat GetCollectionFormat(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name != AttributeNames.ShortName && name != AttributeNames.FullName)
					continue;

				if (attribute.ArgumentList is null)
					return CollectionFormat.Count;

				foreach (AttributeArgumentSyntax arg in attribute.ArgumentList.Arguments)
				{
					if (arg.NameEquals?.Name.Identifier.Text != nameof(GenerateToStringAttribute.CollectionFormat))
						continue;

					Optional<object?> value = semanticModel.GetConstantValue(arg.Expression);

					if (value.HasValue && value.Value is int intValue)
						return (CollectionFormat)intValue;

					break;
				}

				return CollectionFormat.Count;
			}
		}

		return CollectionFormat.Count;
	}
}
