// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a <c>ToString()</c> override for classes marked
/// with the <see cref="GenerateToStringAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ToStringGenerator : IIncrementalGenerator
{
	private static readonly (string MetadataName, string FullName, string ShortName) AttributeNames =
		GeneratorHelpers.GetAttributeNames<GenerateToStringAttribute>();

	private static readonly string ToStringFormatAttributeName = typeof(ToStringFormatAttribute).FullName;
	private static readonly string ToStringOrderAttributeName = typeof(ToStringOrderAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, AttributeNames.MetadataName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		CollectionFormat collectionFormat = GetCollectionFormat(ctx.ClassDeclaration, ctx.SemanticModel);
		string separator = GetSeparator(ctx.ClassDeclaration, ctx.SemanticModel);
		bool formattable = GetFormattable(ctx.ClassDeclaration, ctx.SemanticModel);
		string? nullPlaceholder = GetNullPlaceholder(ctx.ClassDeclaration, ctx.SemanticModel);
		bool includeInherited = GetIncludeInherited(ctx.ClassDeclaration, ctx.SemanticModel);
		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(ctx.ClassDeclaration, ctx.SemanticModel, nameof(GenerateToStringAttribute));
		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, excludedProperties, detectCollections: true, toStringFormatAttributeName: ToStringFormatAttributeName, toStringOrderAttributeName: ToStringOrderAttributeName, includeInherited: includeInherited);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorNames.ToStringGeneratorFullName);
		sb.AppendNullableEnable();
		sb.AppendUsing(NamespaceNames.System);
		sb.AppendUsing(NamespaceNames.SystemCollectionsGeneric);
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, properties, collectionFormat, separator, formattable, nullPlaceholder);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.ToString.g.cs"
			: $"{ctx.ClassName}.ToString.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, ImmutableArray<PropertyDescriptor> properties, CollectionFormat collectionFormat, string separator, bool formattable, string? nullPlaceholder)
	{
		bool hasDictionary = collectionFormat == CollectionFormat.Elements
			&& properties.Any(static p => p.CollectionKind == CollectionKind.Dictionary);

		if (formattable)
			sb.OpenClass(accessibility, className, "IFormattable");
		else
			sb.OpenClass(accessibility, className);

		if (formattable)
		{
			sb.AppendLine("/// <inheritdoc/>");
			sb.AppendLine("public override string ToString()");
			sb.Indent();
			sb.AppendLine("=> ToString(null, null);");
			sb.Outdent();
			sb.AppendLine();
			sb.AppendLine("/// <inheritdoc/>");
			sb.AppendLine("public string ToString(string? format, IFormatProvider? formatProvider)");
			sb.OpenBrace();
			AppendToStringBody(sb, className, properties, collectionFormat, separator, nullPlaceholder, formattable: true);
			sb.CloseBrace();
		}
		else
		{
			sb.AppendLine("/// <inheritdoc/>");
			sb.AppendLine("public override string ToString()");
			sb.OpenBrace();
			AppendToStringBody(sb, className, properties, collectionFormat, separator, nullPlaceholder, formattable: false);
			sb.CloseBrace();
		}

		if (hasDictionary)
		{
			sb.AppendLine();
			AppendDictionaryFormatHelper(sb);
		}

		sb.CloseClass();
	}

	private static void AppendToStringBody(SourceBuilder sb, string className, ImmutableArray<PropertyDescriptor> properties, CollectionFormat collectionFormat, string separator, string? nullPlaceholder, bool formattable)
	{
		if (properties.Length == 0)
		{
			sb.AppendLine($"return \"{className} {{ }}\";");
			return;
		}

		foreach (PropertyDescriptor prop in properties)
		{
			if (prop.CollectionKind == CollectionKind.None)
				continue;
			sb.AppendLine($"string {prop.Name.ToLowerInvariant()} = {BuildCollectionFormatExpression(prop, collectionFormat)};");
		}

		string escapedSeparator = GeneratorHelpers.EscapeString(separator);
		sb.AppendLine("System.Text.StringBuilder sb = new();");
		sb.AppendLine($"sb.Append(\"{className} {{ \");");

		for (int i = 0; i < properties.Length; i++)
		{
			if (i > 0)
				sb.AppendLine($"sb.Append(\"{escapedSeparator}\");");

			PropertyDescriptor prop = properties[i];
			sb.AppendLine($"sb.Append($\"{{nameof({prop.Name})}} = \");");
			sb.AppendLine($"sb.Append({GetValueExpression(prop, nullPlaceholder, formattable)});");
		}

		sb.AppendLine("sb.Append(\" }\");");
		sb.AppendLine("return sb.ToString();");
	}

	private static string GetValueExpression(PropertyDescriptor prop, string? nullPlaceholder, bool formattable)
	{
		if (prop.CollectionKind != CollectionKind.None)
			return prop.Name.ToLowerInvariant();

		if (formattable && prop.IsFormattable)
		{
			if (nullPlaceholder is not null && prop.IsNullable)
			{
				string escaped = GeneratorHelpers.EscapeString(nullPlaceholder);
				return $"({prop.Name}?.ToString(format, formatProvider) ?? \"{escaped}\")";
			}
			string nullConditional = prop.IsNullable ? "?" : "";
			return $"{prop.Name}{nullConditional}.ToString(format, formatProvider)";
		}

		if (nullPlaceholder is not null && prop.IsNullable)
		{
			string escaped = GeneratorHelpers.EscapeString(nullPlaceholder);
			return prop.FormatString is not null
				? $"({prop.Name}?.ToString(\"{prop.FormatString}\") ?? \"{escaped}\")"
				: $"({prop.Name}?.ToString() ?? \"{escaped}\")";
		}

		return prop.FormatString is not null
			? prop.IsNullable
				? $"{prop.Name}?.ToString(\"{prop.FormatString}\")"
				: $"{prop.Name}.ToString(\"{prop.FormatString}\")"
			: prop.Name;
	}

	private static string BuildCollectionFormatExpression(PropertyDescriptor prop, CollectionFormat format)
	{
		bool isImmutableArray = prop.CollectionKind == CollectionKind.ImmutableArray;
		bool isArray = prop.CollectionKind == CollectionKind.Array;
		bool isDictionary = prop.CollectionKind == CollectionKind.Dictionary;

		// ImmutableArray<T> (non-nullable struct): IsValueType = true
		// ImmutableArray<T>? (Nullable<ImmutableArray<T>>): IsValueType = false
		bool isNullableImmutableArray = isImmutableArray && !prop.IsValueType;
		bool isNonNullableImmutableArray = isImmutableArray && prop.IsValueType;

		// Arrays and ImmutableArrays use .Length; all other collection types use .Count
		bool usesLength = isArray || isImmutableArray;

		// Expression for the non-null collection value
		string directAccess = isNullableImmutableArray ? $"{prop.Name}.Value" : prop.Name;
		string countAccess = usesLength ? $"{directAccess}.Length" : $"{directAccess}.Count";

		// Null guard (null means no null check required for non-nullable value types)
		string? nullGuard = isNonNullableImmutableArray
			? null
			: isNullableImmutableArray
				? $"!{prop.Name}.HasValue"
				: $"{prop.Name} == null";

		string WrapGuard(string valueExpr)
			=> nullGuard is not null ? $"{nullGuard} ? \"null\" : {valueExpr}" : valueExpr;

		return format switch
		{
			CollectionFormat.Elements when isDictionary => $"DictionaryToString({prop.Name})",// The DictionaryToString helper handles null internally
			CollectionFormat.Elements => WrapGuard($"\"[\" + string.Join(\", \", {directAccess}) + \"]\""),
			CollectionFormat.Count => WrapGuard($"\"Count = \" + {countAccess}"),
			CollectionFormat.TypeAndCount => WrapGuard($"{directAccess}.GetType().Name + \" (Count = \" + {countAccess} + \")\""),
			_ => prop.Name,
		};
	}

	private static void AppendDictionaryFormatHelper(SourceBuilder sb)
	{
		sb.AppendLine("private static string DictionaryToString<TKey, TValue>(IDictionary<TKey, TValue>? dictionary)");
		sb.OpenBrace();
		sb.AppendLine("if (dictionary == null)");
		sb.Indent();
		sb.AppendLine("return \"null\";");
		sb.Outdent();
		sb.AppendLine("List<string> parts = new List<string>(dictionary.Count);");
		sb.AppendLine("foreach (KeyValuePair<TKey, TValue> kvp in dictionary)");
		sb.Indent();
		sb.AppendLine("parts.Add(kvp.Key + \": \" + kvp.Value);");
		sb.Outdent();
		sb.AppendLine("return \"{\" + string.Join(\", \", parts) + \"}\";");
		sb.CloseBrace();
	}

	private static bool GetFormattable(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
		=> GeneratorHelpers.GetNamedArgumentValue(classDeclaration, semanticModel, AttributeNames.ShortName, AttributeNames.FullName, nameof(GenerateToStringAttribute.Formattable), false);

	private static string GetSeparator(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
		=> GeneratorHelpers.GetNamedArgumentValue(classDeclaration, semanticModel, AttributeNames.ShortName, AttributeNames.FullName, nameof(GenerateToStringAttribute.Separator), ", ");

	private static CollectionFormat GetCollectionFormat(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
		=> (CollectionFormat)GeneratorHelpers.GetNamedArgumentValue(classDeclaration, semanticModel, AttributeNames.ShortName, AttributeNames.FullName, nameof(GenerateToStringAttribute.CollectionFormat), (int)CollectionFormat.Count);

	private static string? GetNullPlaceholder(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
		=> GeneratorHelpers.GetNamedArgumentValue<string?>(classDeclaration, semanticModel, AttributeNames.ShortName, AttributeNames.FullName, nameof(GenerateToStringAttribute.NullPlaceholder), null);

	private static bool GetIncludeInherited(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
		=> GeneratorHelpers.GetNamedArgumentValue(classDeclaration, semanticModel, AttributeNames.ShortName, AttributeNames.FullName, nameof(GenerateToStringAttribute.IncludeInherited), false);
}
