// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a <c>ToString()</c> override for classes marked
/// with the <see cref="GenerateToStringAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ToStringGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(ToStringGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateToStringAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		HashSet<string> excludedProperties = GeneratorHelpers.GetExcludedProperties(ctx.ClassDeclaration, ctx.SemanticModel, nameof(GenerateToStringAttribute));
		ImmutableArray<PropertyDescriptor> properties = GeneratorHelpers.GetPropertyDescriptors(ctx.ClassSymbol, excludedProperties);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendNullableEnable();
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, properties);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.ToString.g.cs"
			: $"{ctx.ClassName}.ToString.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, ImmutableArray<PropertyDescriptor> properties)
	{
		sb.OpenClass(accessibility, className);
		sb.AppendLine("/// <inheritdoc/>");
		sb.AppendLine("public override string ToString()");
		sb.OpenBrace();

		if (properties.Length == 0)
			sb.AppendLine($"return \"{className} {{ }}\";");
		else
			sb.AppendLine($"return $\"{className} {{{{ {BuildFormatString(properties)} }}}}\";");

		sb.CloseBrace();
		sb.CloseClass();
	}

	private static string BuildFormatString(ImmutableArray<PropertyDescriptor> properties)
	{
		StringBuilder format = new();

		for (int i = 0; i < properties.Length; i++)
		{
			if (i > 0)
				format.Append(", ");

			format.Append($"{properties[i].Name} = {{{properties[i].Name}}}");
		}

		return format.ToString();
	}
}
