// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;

using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;
using BB84.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a <c>Validate()</c> method for classes marked
/// with the <see cref="GenerateValidatorAttribute"/> attribute. The generated method
/// scans properties for data annotation attributes and emits direct validation checks.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ValidatorGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(ValidatorGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateValidatorAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> GeneratorHelpers.RegisterClassGenerator(context, GeneratorAttributeName, Execute);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (!GeneratorHelpers.TryCreateContext(input, out GeneratorContext ctx))
			return;

		if (ctx.ClassSymbol.IsAbstract)
		{
			Diagnostic diagnostic = Diagnostic.Create(DiagnosticDescriptors.AbstractClassDiagnostic, ctx.ClassDeclaration.Identifier.GetLocation(), ctx.ClassName);
			context.ReportDiagnostic(diagnostic);
			return;
		}

		ImmutableArray<PropertyValidationInfo> validatedProperties = GetValidatedProperties(ctx.ClassSymbol);

		SourceBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendNullableEnable();
		sb.AppendUsing("System.Collections.Generic");
		sb.AppendUsing("System.ComponentModel.DataAnnotations");
		sb.AppendUsing("System.Text.RegularExpressions");
		sb.AppendLine();
		sb.OpenNamespace(ctx.NamespaceName);
		sb.OpenOuterClasses(ctx.OuterClasses);

		bool implementsIValidatableObject = ImplementsIValidatableObject(ctx.ClassSymbol);
		AppendPartialClass(sb, ctx.ClassName, ctx.Accessibility, validatedProperties, implementsIValidatableObject);

		sb.CloseOuterClasses(ctx.OuterClasses);
		sb.CloseNamespace();

		string hintName = ctx.OuterClasses.Count > 0
			? $"{string.Join(".", ctx.OuterClasses.Select(o => o.Name))}.{ctx.ClassName}.Validator.g.cs"
			: $"{ctx.ClassName}.Validator.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(SourceBuilder sb, string className, string accessibility, ImmutableArray<PropertyValidationInfo> validatedProperties, bool implementsIValidatableObject)
	{
		sb.OpenClass(accessibility, className);

		// Generate Validate() returning Dictionary<string, List<string>>
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Validates the current instance and returns a dictionary of validation errors grouped by property name.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <returns>A dictionary where each key is a property name and the value is a list of validation error messages. An empty dictionary indicates a valid instance.</returns>");
		sb.AppendLine("public Dictionary<string, List<string>> Validate()");
		sb.OpenBrace();
		sb.AppendLine("Dictionary<string, List<string>> errors = new Dictionary<string, List<string>>();");

		foreach (PropertyValidationInfo property in validatedProperties)
		{
			foreach (ValidationRule rule in property.Rules)
			{
				AppendValidationRule(sb, property.Name, property.TypeName, property.IsCollection, property.IsArray, rule);
			}
		}

		if (implementsIValidatableObject)
		{
			sb.AppendLine();
			sb.AppendLine("foreach (ValidationResult validationResult in ((IValidatableObject)this).Validate(new ValidationContext(this)))");
			sb.OpenBrace();
			sb.AppendLine("if (validationResult != ValidationResult.Success)");
			sb.OpenBrace();
			sb.AppendLine("string errorMessage = validationResult.ErrorMessage ?? \"Validation failed.\";\n");
			sb.AppendLine("if (validationResult.MemberNames != null)");
			sb.OpenBrace();
			sb.AppendLine("foreach (string memberName in validationResult.MemberNames)");
			sb.OpenBrace();
			sb.AppendLine("if (!errors.ContainsKey(memberName))");
			sb.Indent();
			sb.AppendLine("errors[memberName] = new List<string>();");
			sb.Outdent();
			sb.AppendLine("errors[memberName].Add(errorMessage);");
			sb.CloseBrace();
			sb.CloseBrace();
			sb.CloseBrace();
			sb.CloseBrace();
		}

		sb.AppendLine("return errors;");
		sb.CloseBrace();
		sb.AppendLine();

		// Generate Validate(string propertyName) returning List<string>
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Validates a specific property of the current instance and returns a list of validation errors.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <param name=\"propertyName\">The name of the property to validate.</param>");
		sb.AppendLine("/// <returns>A list of validation error messages for the specified property. An empty list indicates the property is valid.</returns>");
		sb.AppendLine("public List<string> Validate(string propertyName)");
		sb.OpenBrace();
		sb.AppendLine("Dictionary<string, List<string>> allErrors = Validate();");
		sb.AppendLine("if (allErrors.TryGetValue(propertyName, out List<string>? propertyErrors))");
		sb.Indent();
		sb.AppendLine("return propertyErrors;");
		sb.Outdent();
		sb.AppendLine("return new List<string>();");
		sb.CloseBrace();
		sb.CloseClass();
	}

	private static void AppendValidationRule(SourceBuilder sb, string propertyName, string typeName, bool isCollection, bool isArray, ValidationRule rule)
	{
		sb.AppendLine();

		switch (rule.Kind)
		{
			case ValidationKind.Required:
				AppendRequiredValidation(sb, propertyName, typeName, rule);
				break;
			case ValidationKind.Range:
				AppendRangeValidation(sb, propertyName, isCollection, isArray, rule);
				break;
			case ValidationKind.StringLength:
				AppendStringLengthValidation(sb, propertyName, rule);
				break;
			case ValidationKind.MinLength:
				AppendMinLengthValidation(sb, propertyName, rule);
				break;
			case ValidationKind.MaxLength:
				AppendMaxLengthValidation(sb, propertyName, rule);
				break;
			case ValidationKind.RegularExpression:
				AppendRegularExpressionValidation(sb, propertyName, rule);
				break;
			case ValidationKind.EmailAddress:
				AppendEmailAddressValidation(sb, propertyName, rule);
				break;
			case ValidationKind.Url:
				AppendUrlValidation(sb, propertyName, rule);
				break;
			case ValidationKind.Phone:
				AppendPhoneValidation(sb, propertyName, rule);
				break;
			case ValidationKind.CreditCard:
				AppendCreditCardValidation(sb, propertyName, rule);
				break;
			case ValidationKind.Compare:
				AppendCompareValidation(sb, propertyName, rule);
				break;
			case ValidationKind.CustomValidation:
				AppendCustomValidation(sb, propertyName, rule);
				break;
		}
	}

	private static void AppendRequiredValidation(SourceBuilder sb, string propertyName, string typeName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The {propertyName} field is required.";

		if (typeName is "string" or "string?")
			sb.AppendLine($"if (string.IsNullOrEmpty({propertyName}))");
		else
			sb.AppendLine($"if ({propertyName} == null)");

		AppendAddError(sb, propertyName, message);
	}

	private static void AppendRangeValidation(SourceBuilder sb, string propertyName, bool isCollection, bool isArray, ValidationRule rule)
	{
		if (isCollection)
		{
			string countAccessor = isArray ? "Length" : "Count";
			string message = rule.ErrorMessage ?? $"The field {propertyName} must have between {rule.MinValue} and {rule.MaxValue} elements.";

			sb.AppendLine($"if ({propertyName} != null && ({propertyName}.{countAccessor} < {rule.MinValue} || {propertyName}.{countAccessor} > {rule.MaxValue}))");
			AppendAddError(sb, propertyName, message);
		}
		else
		{
			string message = rule.ErrorMessage ?? $"The field {propertyName} must be between {rule.MinValue} and {rule.MaxValue}.";

			sb.AppendLine($"if ({propertyName} < {rule.MinValue} || {propertyName} > {rule.MaxValue})");
			AppendAddError(sb, propertyName, message);
		}
	}

	private static void AppendStringLengthValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		if (rule.MinValue is not null)
		{
			string minMessage = rule.ErrorMessage ?? $"The field {propertyName} must be a string with a minimum length of {rule.MinValue} and a maximum length of {rule.MaxValue}.";

			sb.AppendLine($"if ({propertyName} != null && ({propertyName}.Length < {rule.MinValue} || {propertyName}.Length > {rule.MaxValue}))");
			AppendAddError(sb, propertyName, minMessage);
		}
		else
		{
			string message = rule.ErrorMessage ?? $"The field {propertyName} must be a string with a maximum length of {rule.MaxValue}.";

			sb.AppendLine($"if ({propertyName} != null && {propertyName}.Length > {rule.MaxValue})");
			AppendAddError(sb, propertyName, message);
		}
	}

	private static void AppendMinLengthValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The field {propertyName} must be a string or collection with a minimum length of {rule.MinValue}.";

		sb.AppendLine($"if ({propertyName} != null && {propertyName}.Length < {rule.MinValue})");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendMaxLengthValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The field {propertyName} must be a string or collection with a maximum length of {rule.MaxValue}.";

		sb.AppendLine($"if ({propertyName} != null && {propertyName}.Length > {rule.MaxValue})");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendRegularExpressionValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The field {propertyName} must match the regular expression '{GeneratorHelpers.EscapeString(rule.Pattern!)}'.";

		sb.AppendLine($"if ({propertyName} != null && !Regex.IsMatch({propertyName}, @\"{GeneratorHelpers.EscapeVerbatimString(rule.Pattern!)}\"))");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendEmailAddressValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The {propertyName} field is not a valid e-mail address.";

		sb.AppendLine($"if ({propertyName} != null && !Regex.IsMatch({propertyName}, @\"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$\"))");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendUrlValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The {propertyName} field is not a valid fully-qualified http, https, or ftp URL.";

		sb.AppendLine($"if ({propertyName} != null && !Regex.IsMatch({propertyName}, @\"^https?://|^ftp://\", RegexOptions.IgnoreCase))");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendPhoneValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The {propertyName} field is not a valid phone number.";

		sb.AppendLine($"if ({propertyName} != null && !Regex.IsMatch({propertyName}, @\"^[\\+]?[\\d\\s\\-\\(\\)\\.]+$\"))");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendCreditCardValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string message = rule.ErrorMessage ?? $"The {propertyName} field is not a valid credit card number.";

		// Luhn algorithm check at runtime
		sb.AppendLine($"if ({propertyName} != null)");
		sb.OpenBrace();
		sb.AppendLine($"string digits = {propertyName}.Replace(\"-\", \"\").Replace(\" \", \"\");");
		sb.AppendLine("bool ccValid = digits.Length > 0 && digits.All(char.IsDigit);");
		sb.AppendLine("if (ccValid)");
		sb.OpenBrace();
		sb.AppendLine("int sum = 0;");
		sb.AppendLine("bool alternate = false;");
		sb.AppendLine("for (int i = digits.Length - 1; i >= 0; i--)");
		sb.OpenBrace();
		sb.AppendLine("int n = digits[i] - '0';");
		sb.AppendLine("if (alternate)");
		sb.OpenBrace();
		sb.AppendLine("n *= 2;");
		sb.AppendLine("if (n > 9) n -= 9;");
		sb.CloseBrace();
		sb.AppendLine("sum += n;");
		sb.AppendLine("alternate = !alternate;");
		sb.CloseBrace();
		sb.AppendLine("ccValid = sum % 10 == 0;");
		sb.CloseBrace();
		sb.AppendLine("if (!ccValid)");
		AppendAddError(sb, propertyName, message);
		sb.CloseBrace();
	}

	private static void AppendCompareValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string otherProperty = rule.CompareProperty!;
		string message = rule.ErrorMessage ?? $"'{propertyName}' and '{otherProperty}' do not match.";

		sb.AppendLine($"if (!Equals({propertyName}, {otherProperty}))");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendCustomValidation(SourceBuilder sb, string propertyName, ValidationRule rule)
	{
		string attributeTypeName = rule.CustomAttributeTypeName!;
		string message = rule.ErrorMessage ?? $"The field {propertyName} is invalid.";

		sb.AppendLine($"if (!new {attributeTypeName}().IsValid({propertyName}))");
		AppendAddError(sb, propertyName, message);
	}

	private static void AppendAddError(SourceBuilder sb, string propertyName, string message)
	{
		sb.OpenBrace();
		sb.AppendLine($"if (!errors.ContainsKey(nameof({propertyName})))");
		sb.Indent();
		sb.AppendLine($"errors[nameof({propertyName})] = new List<string>();");
		sb.Outdent();
		sb.AppendLine($"errors[nameof({propertyName})].Add(\"{GeneratorHelpers.EscapeString(message)}\");");
		sb.CloseBrace();
	}

	private static ImmutableArray<PropertyValidationInfo> GetValidatedProperties(INamedTypeSymbol classSymbol)
	{
		ImmutableArray<PropertyValidationInfo>.Builder builder = ImmutableArray.CreateBuilder<PropertyValidationInfo>();
		HashSet<string> seen = [];

		foreach (IPropertySymbol propertySymbol in GeneratorHelpers.GetPublicPropertySymbols(classSymbol, includeInherited: true, requireGetter: true))
		{
			if (!seen.Add(propertySymbol.Name))
				continue;

			ImmutableArray<ValidationRule>.Builder rules = ImmutableArray.CreateBuilder<ValidationRule>();

			foreach (AttributeData attribute in propertySymbol.GetAttributes())
			{
				string? attributeName = attribute.AttributeClass?.ToDisplayString();

				if (attributeName is null)
					continue;

				ValidationRule? rule = attributeName switch
				{
					DataAnnotationNames.Required => ParseRequiredAttribute(attribute),
					DataAnnotationNames.Range => ParseRangeAttribute(attribute),
					DataAnnotationNames.StringLength => ParseStringLengthAttribute(attribute),
					DataAnnotationNames.MinLength => ParseMinLengthAttribute(attribute),
					DataAnnotationNames.MaxLength => ParseMaxLengthAttribute(attribute),
					DataAnnotationNames.RegularExpression => ParseRegularExpressionAttribute(attribute),
					DataAnnotationNames.EmailAddress => ParseSimpleAttribute(attribute, ValidationKind.EmailAddress),
					DataAnnotationNames.Url => ParseSimpleAttribute(attribute, ValidationKind.Url),
					DataAnnotationNames.Phone => ParseSimpleAttribute(attribute, ValidationKind.Phone),
					DataAnnotationNames.CreditCard => ParseSimpleAttribute(attribute, ValidationKind.CreditCard),
					DataAnnotationNames.Compare => ParseCompareAttribute(attribute),
					_ => TryParseCustomValidationAttribute(attribute)
				};

				if (rule is not null)
					rules.Add(rule);
			}

			if (rules.Count > 0)
			{
				string typeName = propertySymbol.Type.ToMinimalDisplayString();
				bool isCollection = IsCollectionType(propertySymbol.Type);
				bool isArray = propertySymbol.Type.TypeKind == TypeKind.Array;
				builder.Add(new PropertyValidationInfo(propertySymbol.Name, typeName, isCollection, isArray, rules.ToImmutable()));
			}
		}

		return builder.ToImmutable();
	}

	private static ValidationRule ParseRequiredAttribute(AttributeData attribute)
	{
		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.Required) { ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseRangeAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 2)
			return null;

		string? minValue = args[0].Value?.ToString();
		string? maxValue = args[1].Value?.ToString();

		if (minValue is null || maxValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.Range) { MinValue = minValue, MaxValue = maxValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseStringLengthAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? maxValue = args[0].Value?.ToString();

		if (maxValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		int? minLengthValue = GetNamedArgumentValue<int>(attribute, "MinimumLength");
		string? minValue = minLengthValue?.ToString(System.Globalization.CultureInfo.InvariantCulture);

		return new ValidationRule(ValidationKind.StringLength) { MaxValue = maxValue, MinValue = minValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseMinLengthAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? minValue = args[0].Value?.ToString();

		if (minValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.MinLength) { MinValue = minValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseMaxLengthAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? maxValue = args[0].Value?.ToString();

		if (maxValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.MaxLength) { MaxValue = maxValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseRegularExpressionAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? pattern = args[0].Value?.ToString();

		if (pattern is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.RegularExpression) { Pattern = pattern, ErrorMessage = errorMessage };
	}

	private static ValidationRule ParseSimpleAttribute(AttributeData attribute, ValidationKind kind)
	{
		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");
		return new ValidationRule(kind) { ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseCompareAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? otherProperty = args[0].Value?.ToString();

		if (otherProperty is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.Compare) { CompareProperty = otherProperty, ErrorMessage = errorMessage };
	}

	private static ValidationRule? TryParseCustomValidationAttribute(AttributeData attribute)
	{
		if (attribute.AttributeClass is null)
			return null;

		// Check if this attribute inherits from ValidationAttribute
		INamedTypeSymbol? baseType = attribute.AttributeClass.BaseType;
		bool isValidationAttribute = false;

		while (baseType is not null)
		{
			if (baseType.ToDisplayString() == DataAnnotationNames.ValidationAttribute)
			{
				isValidationAttribute = true;
				break;
			}

			baseType = baseType.BaseType;
		}

		if (!isValidationAttribute)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");
		string attributeTypeName = attribute.AttributeClass.ToDisplayString();

		return new ValidationRule(ValidationKind.CustomValidation) { CustomAttributeTypeName = attributeTypeName, ErrorMessage = errorMessage };
	}

	private static bool ImplementsIValidatableObject(INamedTypeSymbol classSymbol)
	{
		foreach (INamedTypeSymbol iface in classSymbol.AllInterfaces)
		{
			if (iface.ToDisplayString() == DataAnnotationNames.IValidatableObject)
				return true;
		}

		return false;
	}

	private static T? GetNamedArgumentValue<T>(AttributeData attribute, string name)
	{
		foreach (KeyValuePair<string, TypedConstant> namedArgument in attribute.NamedArguments)
		{
			if (namedArgument.Key == name && namedArgument.Value.Value is T value)
				return value;
		}

		return default;
	}

	private static bool IsCollectionType(ITypeSymbol type)
	{
		if (type.TypeKind == TypeKind.Array)
			return true;

		if (type.SpecialType == SpecialType.System_String)
			return false;

		foreach (INamedTypeSymbol iface in type.AllInterfaces)
		{
			if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
				return true;
		}

		return type is INamedTypeSymbol namedType && namedType.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T;
	}

	private enum ValidationKind
	{
		Required,
		Range,
		StringLength,
		MinLength,
		MaxLength,
		RegularExpression,
		EmailAddress,
		Url,
		Phone,
		CreditCard,
		Compare,
		CustomValidation
	}

	private sealed class ValidationRule(ValidationKind kind)
	{
		public ValidationKind Kind { get; } = kind;
		public string? MinValue { get; set; }
		public string? MaxValue { get; set; }
		public string? Pattern { get; set; }
		public string? ErrorMessage { get; set; }
		public string? CompareProperty { get; set; }
		public string? CustomAttributeTypeName { get; set; }
	}

	private readonly struct PropertyValidationInfo(string name, string typeName, bool isCollection, bool isArray, ImmutableArray<ValidatorGenerator.ValidationRule> rules)
	{
		public string Name { get; } = name;
		public string TypeName { get; } = typeName;
		public bool IsCollection { get; } = isCollection;
		public bool IsArray { get; } = isArray;
		public ImmutableArray<ValidationRule> Rules { get; } = rules;
	}
}
