// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using BB84.SourceGenerators.Helpers;

namespace BB84.SourceGenerators.Tests.Helpers;

[TestClass]
public sealed class AttributeSourceRewriterTests
{
	private const string EqualityResource = "GenerateEqualityAttribute.cs";

	[TestMethod]
	public void TransformShouldPrependAutoGeneratedHeaderAndNullableEnable()
	{
		string result = AttributeSourceRewriter.ReadAndTransform(EqualityResource);

		Assert.Contains("<auto-generated>", result);
		Assert.Contains("#nullable enable", result);
	}

	[TestMethod]
	public void TransformShouldKeepNamespaceAndTypeButRemoveUsingsAndLicense()
	{
		string result = AttributeSourceRewriter.ReadAndTransform(EqualityResource);

		Assert.Contains("namespace BB84.SourceGenerators.Attributes", result);
		Assert.Contains("class GenerateEqualityAttribute", result);
		// No using directives survive (all types are fully qualified instead).
		Assert.DoesNotContain("using ", result);
		// The MIT license header comment is stripped.
		Assert.DoesNotContain("licensed under the MIT", result);
	}

	[TestMethod]
	public void TransformShouldEmitInternalAttributeType()
	{
		string result = AttributeSourceRewriter.ReadAndTransform(EqualityResource);

		Assert.Contains("internal sealed class GenerateEqualityAttribute", result);
	}

	[TestMethod]
	public void TransformShouldFullyQualifyKnownSystemTypes()
	{
		string result = AttributeSourceRewriter.ReadAndTransform(EqualityResource);

		// [AttributeUsage(AttributeTargets.Class, ...)] : Attribute  ->  fully qualified System.* forms.
		Assert.Contains("System.AttributeUsage", result);
		Assert.Contains("System.AttributeTargets", result);
		Assert.Contains("System.Attribute", result);
	}

	[TestMethod]
	public void TransformShouldConvertFileScopedNamespaceToBlockScoped()
	{
		string result = AttributeSourceRewriter.ReadAndTransform(EqualityResource);

		// Source uses a file-scoped namespace (trailing ';'); output must be block-scoped.
		Assert.DoesNotContain("namespace BB84.SourceGenerators.Attributes;", result);
	}

	[TestMethod]
	[DataRow("GenerateEqualityAttribute.cs")]
	[DataRow("GenerateToStringAttribute.cs")]
	[DataRow("GenerateBuilderAttribute.cs")]
	[DataRow("GenerateNotificationsAttribute.cs")]
	[DataRow("GenerateSingletonAttribute.cs")]
	[DataRow("GenerateCloneableAttribute.cs")]
	public void TransformShouldProduceCompilableInternalTypeForEachAttribute(string resourceName)
	{
		string result = AttributeSourceRewriter.ReadAndTransform(resourceName);

		Assert.IsFalse(string.IsNullOrWhiteSpace(result));
		Assert.Contains("internal", result);
		Assert.Contains("namespace BB84.SourceGenerators.Attributes", result);
		Assert.DoesNotContain("using ", result);
	}
}
